Fantom-foundation/Tosca

.github/workflows/go.yml

This PR switches the CI testing for Go changes back to github hosted resources.

Switch CI to github hosted resources

---

go/ct/driver/generator_info.go
go/ct/driver/main.go
go/ct/rlz/rules.go
go/ct/rlz/rules_test.go

This PR adds a sub-command to the CT driver providing insights into the factors contributing to the number of test cases generated from each rule. An example is shown here:
```
----- Rule: extcodecopy_regular_cold -----
Conditions:
Gas ≥ 2600: 8
code[PC] = EXTCODECOPY: 2
cold(param[0]): 2
revision(Berlin-UnknownNextRevision): 4
revision(Istanbul-London): 4
stackSize ≤ 1024: 4
stackSize ≥ 4: 5
status = running: 4
Parameters:
0: 2
1: 5
2: 5
3: 5
Total number of cases: 10240000
Share of total rules: 1.0%
```
The intention of this utility is to aid the tuning of the test case generation process.

Add sub-command to list rule generation information

---

go/ct/driver/run.go
go/ct/rlz/conditions.go
go/ct/rlz/domains.go
go/ct/rlz/expressions.go
go/ct/rlz/expressions_test.go
go/ct/rlz/property.go
go/ct/rlz/rules.go
go/ct/rlz/rules_test.go
go/ct/rlz/test_value.go
go/ct/rlz/test_value_test.go
go/ct/spc/specification_test.go

This improvement to the test case generation process fixes support for constraints where there are multiple constraints for the same property of the state. 
Before this change, when enumerating test cases for a constraint of the form
`stackSize ≥ 3 ∧ stackSize ≤ 1024`
both clauses would be independently asked for example-stack-sizes to be used in test states. Those may have been, for instance, the values `{0, 2, 3, 4, 1024}` for the first clause and `{0, 1023, 1024}` for the second clause. From those sets, due to the implicit combination of constraints yield by both constraints, the intersection was formed and tested. In the given example, this would result in the set `{0, 1024}` as values for actual test cases, ignoring the values being closer to the boundary limits.
With this change, …

Make properties in test case enumeration explicit

---

go/ct/common/slices.go
go/ct/common/slices_test.go
go/ct/gen/stack.go
go/ct/spc/specification.go
go/ct/st/code.go
go/ct/st/code_test.go
go/ct/utils/adapter.go
go/ct/utils/adapter_test.go
go/vm/lfvm/converter.go
go/vm/lfvm/ct.go
go/vm/test/integration_test.go

This PR attempts to reduce the amount of times the pattern `make`+`copy` is called. replacing it by either `clone` or `PadSlice`.
This PR Fixes  #359

CT: reduce make+copy pattern

---

go/ct/spc/specification.go
go/vm/geth/ct.go

This PR adds support for static contexts to the CALL expression specification.
This contributes to #380 
Todo:

Add support for static-call semantic in CALL op specification

---

go/ct/rlz/rules.go
go/ct/st/stack.go
go/ct/st/state.go
go/ct/st/state_test.go
go/vm/evmc/evmc_steppable_interpreter.go
go/vm/evmc/evmc_steppable_interpreter_test.go
go/vm/geth/ct.go
go/vm/lfvm/ct.go
go/vm/lfvm/ct_test.go

In the profile of the CT run, stack memory allocation still had a big impact on the runtime. Stacks were garbage collected and therefore had to be newly allocated. 
This PR fixes this and returns all stacks, memory allocations are no longer visible in the profile.

Improve Stack Pool

---

go/ct/spc/enumeration_test.go

While the number of executed tests after an abort is quite consistent on local machines, it has high fluctuations on the CI server. This PR loosens the requirements and only checks that less tests are executed than in a normal run.

Fix flaky abort enumeration test

---

go/ct/common/revisions.go
go/ct/gen/range_solver.go
go/ct/gen/range_solver_test.go
go/ct/gen/stack.go
go/ct/gen/stack_test.go
go/ct/gen/state.go
go/ct/gen/state_test.go
go/ct/rlz/conditions.go
go/ct/rlz/expressions.go
go/ct/rlz/expressions_test.go

This PR introduces a new `RangeSolver` utility capable of handling range constraints of the shape
```
constraint ::= true | constraint ∧ clause
clause     ::= X op C
op         ::= < | ≤ | = | ≥ | >
```
where `X` is a numeric property to be solved for and `C` are constants.
This common range solver is integrated into the `StateGenerator` to cover `Gas`, `GasRefund`, `Revision`, and `StackSize` constraints. By doing so, also the terminology used for defining constraints on those parameters was aligned.

Unifies handling of range constraints

---

go/ct/common/revisions.go
go/ct/driver/run.go
go/ct/spc/specification.go
go/ct/utils/adapter.go
go/vm/evmc/evmc_interpreter.go
go/vm/evmone/evmone.go
go/vm/evmzero/ct.go
go/vm/evmzero/evmzero.go
go/vm/geth/ct.go
go/vm/geth/geth.go
go/vm/interpreter.go
go/vm/lfvm/ct.go
go/vm/lfvm/lfvm.go
go/vm/test/revision_test.go

This PR introduces a custom error type for unsupported revisions.
Fixes #320.
Further a newest supported revision for the CT specification is introduced. This ensures that rules that do not change with new revisions still produce test cases with new them.

Unsupported Revision Error

---

go/ct/rlz/domains.go
go/ct/rlz/expressions.go
go/ct/spc/specification.go

This PR reduces the number of test samples for value parameters of Call expressions from 11 to 3.
Number of test cases before: 2141852308
Number of test cases after: 748393108 (-65%)

Restrict domain for value parameters in Call rules

---

cpp/vm/evmzero/interpreter.cc
cpp/vm/evmzero/interpreter_test.cc
go/vm/lfvm/instructions.go
go/vm/lfvm/instructions_test.go

LFVM and evmzero did not handle the CREATE instruction correctly if a value higher than the accounts balance has been sent. This is fixed with this PR.
Regression tests are going to be added with the addition of the CREATE instruction to the CT in #441.

Check balance in VM create implementations

---

go/ct/driver/run.go

If something is off in the specification it can happen that millions of errors are detected. In such cases, the driver would crash with an out-of-memory errors.
There is usually no need to ever produce that many issues, thus this PR reduces the default limit for errors to 100.

Add default limit to number of errors

---

go/ct/common/opcodes.go
go/ct/spc/specification.go
go/ct/st/call_journal.go
go/vm/geth/ct.go
go/vm/lfvm/instructions.go

This PR adds the CREATE2 opcode to the CT specification. 
Fixes #385.

CT: add CREATE2 to specification

---

go/ct/driver/common.go
go/ct/driver/main.go
go/ct/driver/probe.go
go/ct/driver/run.go
go/ct/driver/stats.go
go/ct/gen/code.go

This PR adds a `probe` sub-command testing random states for
- being covered by the specification (complete)
- having a consistently specified successor state (sound)
- being correctly handled by a selected interpreter implementation
The aim for this utility is to find specification errors, when targeting `geth`, or implementation errors, when targeting any other interpreter implementation.

Add sub-command for testing random test states

---

go/ct/st/serialization_test.go
go/ct/st/state_test.go

Using a table driven approach to test the st state `Eq`, `Diff` and `Clone` functions.
Each field is only changed in one way, because the fields implementation of equal and diff is already tested with its own unit tests.
Fixes #433.

Refactor st state tests

---

cpp/vm/evmzero/interpreter.cc
cpp/vm/evmzero/interpreter_test.cc
regression_inputs/blockhash_#461.json

This PR fixes the BLOCKHASH operation by adding a check that the number of the block to be hashed is within 256 of the current block.
This PR adds a test for the case when the block to be hashed is outside of this range, in this case the returned hash is 0 and a regression test case for the CT.

evmzero:  Add check for range in blockHash op

---

go/ct/driver/cli/utils.go
go/ct/driver/generator_info.go
go/ct/driver/list.go
go/ct/driver/run.go
go/ct/driver/stats.go
go/ct/driver/stats_test.go
go/ct/driver/test.go

This PR refactors command line arguments from the CT driver into a single module. 
Adds short form for some of them:
- filter: f
- jobs: j
- seed: s
cpuprofile argument must include a file
Add Filter option to stats command.

Refactor CT driver arguments into a single definition module. 

---

go.mod
go.sum

This PR replaces the dependency to `tosca-go-ethereum` with the new `go-ethereum-sonic` repository which is intended to be the common foundation for all Fantom projects from now on.

Switch to new go-ethereum-sonic repository

---

go/ct/common/revisions.go
go/ct/common/revisions_test.go

We noticed that since each revision was getting only 10 block number, this would be a problem for generating states with block numbers over  30. (or 50 with the new revisions). Because of this we decided to increase the range of block number per revision to 1000. This should be sufficient for the current tests, and generating interesting states. 
This PR contributes to  #459

CT: Increase range of block number per revision

---

go/ct/evm_test.go

This test was relying on the random number generator using always the same seed and being used the same number of times. As elements were added to the state generator, this test stopped working. With this fix we can always ensure that the test runs with states generated with supported revision by the CT and the implementations.

CT: define boundaries on the revision to be used in explicit test cases

---

go.mod
go.sum
go/vm/lfvm/converter.go
go/vm/lfvm/converter_test.go

This PR replaces the former unbound cache for converted codes in the LFVM interpreter with a fixed-sized LRU cache. Additionally, some unnecessary debug code was removed.
This fixes #314.
The PR also adds benchmarks for the cache to identify the performance impact:
```
goos: linux
goarch: amd64
pkg: github.com/Fantom-foundation/Tosca/go/vm/lfvm
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
ConversionCacheLookupSpeed-12   31.61n ± 4%   51.20n ± 4%  +61.97% (p=0.000 n=10)
ConversionCacheUpdateSpeed-12   573.1n ± 6%   427.7n ± 6%  -25.38% (p=0.000 n=10)
geomean                         134.6n        148.0n        +9.94%
│   old.txt    │               new.txt                │
│     B/op …
```

Replace unbounded code conversion cache with limited LRU cache

---

go/ct/common/opcodes.go
go/ct/gen/state.go
go/ct/gen/state_test.go
go/ct/st/serialization.go
go/ct/st/serialization_test.go
go/ct/st/state.go
go/ct/st/state_test.go
go/ct/utils/adapter.go
go/vm/geth/geth.go

This PR adds a list of the last 256 blocks' hashes to the CT's state and the opcode for `BLOCKHASH`. 
This list of hashes will be needed for the implementation of the rule, but since it can be in its own PR for ease of read and understanding. 
This PR contributes to #459

CT: Add recent block hashes to state, and generator

---

go/ct/gen/interval_solver.go
go/ct/gen/interval_solver_test.go

This PR adds an interval solver. This tool can be used to describe a set of intervals and get a random number uniformly from all the possible values considering all the intervals. 
This PR contributes to #459

CT: Add interval solver

---

go/ct/gen/interval_solver_test.go

This PR fixes the seed for an unstable test.
Since the test aims to randomly generate all the values inside the range, it is hard to ensure how many iterations are needed for this. 
One options is to fix the seed, hence ensuring the same sequence of random numbers.
Another alternative would be to keep iterating until all the elements in the range have been generated at least once.
Let me know if you think this suffices or I should implement the second alternative.

CT: Fix Interval flaky test

---

go/ct/evm_test.go
go/ct/utils/adapter.go
go/vm/evmzero/evmzero.go

This PR fixes the `ExplicitCases` test for `JUMP` and `JUMPI` instructions by forcing it to run with all the supported revisions, and updates the evmzero adapter to support Shangai as well.
This problem was hidden by the random number generator only generating revisions older than Shangai

CT: fix jump/i explicit test and evmzero adapter

---

go/vm/test/vm_test.go

A minor change repairing the setup of a benchmark which, due to recent changes, has additional dependencies.

Create non-nil context for empty benchmark

---

go/ct/common/opcodes.go
go/ct/common/opcodes_test.go

Due to the huge state space finding missing opcodes requires the evaluation of millions of states. A simple check is introduced which ensures that the number of defined opcodes is consistent with evm codes website.
Has to be merged after the implementation of BLOCKHASH.

Add check ensuring the right number of opcodes

---

cpp/vm/evmzero/evmzero.cc
cpp/vm/evmzero/interpreter.cc
cpp/vm/evmzero/interpreter.h
cpp/vm/evmzero/interpreter_test.cc

Starting with Shanghai, the init code of a create call can no longer have arbitrary size. These changes are added to the evmzero create/create2 implementations.
Contributes to #489.

evmzero: Limit init code size

---

go/vm/lfvm/ct.go
go/vm/lfvm/instructions.go
go/vm/lfvm/instructions_test.go
go/vm/lfvm/interpreter.go
go/vm/lfvm/memory.go

Starting with Shanghai, the init code of a create call can no longer have arbitrary size. These changes are added to the LFVM create/create2 implementations.
Contributes to #489.

LFVM: Add init code size check

---

go/ct/rlz/parameters.go
go/ct/spc/specification.go

Starting with Shanghai, the init code of a create call can no longer have arbitrary size. These changes are added to the create/create2 effect implementation.
Fixes #489, can only be merged after #498 and #499 to ensure correct CT execution.

CT: Add create init code limit

---

go/ct/common/opcodes.go
go/ct/common/opcodes_test.go
go/ct/spc/specification.go
go/ct/spc/specification_map.go
go/ct/spc/specification_test.go

This PR adds:
- a test to check for specification soundness
- a rule that checks that when the PC is pointing at data, nothing gets executed
- a rule for each of the 256 available codes in the 2 byte spectrum, and checking the invalid codes are treated properly.

CT: Specification Soundness test

---

go/ct/evm_test.go
go/ct/gen/code.go
go/ct/gen/code_test.go

What does this solve?  
The unit test would have failed because of creating a code buffer of size 1 to store 2 instructions.
What does this not solve: 
It is still not possible to additionally set the Pc to a constant direction, this would require to generate the Pc at a different point in time and account for it. This is not needed right now.
fixes #507

Fix Flaky unittest, allocate enough space for all needed opCodes

---

go/vm/lfvm/instructions_test.go
go/vm/lfvm/memory.go
go/vm/lfvm/memory_test.go

Use the same method as [Geth](https://github.com/Fantom-foundation/tosca-go-ethereum/blob/4db0f269681aa0137a5510532a8c4f0c423237e7/core/vm/gas_table.go#L39):
- Verify that overflow can still not happen, although LFVM gas is signed. 
- This is related to #524, may need to be reverted to investigate the cause of the CT not detecting this bug.

Prevent gas oveflow in the memory expansion cost computation

---

go/ct/spc/enumeration.go

This commit prints enumeration status one last time before exiting. This is useful when running small filtered ct executions, to read the number of executed states.
A low-hanging fruit that improves tool usage:
- Filters resulting in an empty set will not warn about it but only report success, now the count of states can be seen.
- It is nice to see the final state count instead of the number 5 seconds before, and the completion time.

CT driver, print progress before exit.

---

go/ct/gen/state.go
go/ct/gen/storage.go
go/ct/gen/storage_test.go
go/ct/rlz/conditions.go
go/ct/rlz/conditions_test.go
go/ct/spc/specification.go
go/ct/spc/specification_test.go
go/vm/world_state.go

This PR fixes the storage generation, in particular when using `StorageAssigned` config.
it also changes:
- use vm.StorageStatus, moves print of `StorageCfg`  to `world_state.go`
- add tests for missing StorageAssigned config
- add tests for triggering status 
This should fix the flakiness of the test `TestSpecification_EachRuleProducesAMatchingTestCase`

CT: Fix storage generation

---

go/ct/rlz/parameters.go

This PR is a response to the test `TestSpecification_EachRuleProducesAMatchingTestCase` taking too long for the development cycle compared to other tests.
Running the commands
```
go test ./go/ct/spc -run ^TestSpecification_EachRuleProducesAMatchingTestCase$ -cpuprofile cpu.log
go tool pprof -http "localhost:8000" ./cpu.log
````
and a followed analysis showed that `MemorySizeParameter.Samples()`  took about 30% of the whole run.
Making the slice a global variable to prevent multiple allocations reduced the runtime of the whole test in ~45%
Making the slice for `MemoryOffsetParameter.Samples()` reusable as well reduced another ~5%. 
The rest of the parameters are made reusable as well for consistency. 
This change is "safe" only because the `.Samples` methods are only called in a `for _, …

CT: reusable sample slices

---

go/ct/common/address.go
go/ct/rlz/conditions.go
go/ct/rlz/conditions_test.go
go/ct/st/accounts.go

This PR is a response to the test `TestSpecification_EachRuleProducesAMatchingTestCase` taking too long for the development cycle compared to other tests. 
Running the commands
```
go test ./go/ct/spc -run ^TestSpecification_EachRuleProducesAMatchingTestCase$ -cpuprofile cpu.log
go tool pprof -http "localhost:8000" ./cpu.log
```
and a followed analysis showed  that `IsAddressWarm` and the `Cold` counterpart were taking about 21% of the whole run. 
Unfortunately the changes proposed in this PR only lowered this to 17% of the full run of the test, but this results are not shown in the benchmark comparisons. 
That said, I do think these changes do help code maintainability.

CT: IsAddressWarm/Cold small refactor & benchmark

---

cpp/vm/evmzero/interpreter.cc
go/vm/evmc/evmc_interpreter.go
go/vm/evmc/evmc_steppable_interpreter.go
go/vm/evmzero/evmzero_test.go

This PR adds `EvmcBlobHashes []evmc.Hash` to `HostContext`  in `evmc_interpreter`.
These slice is filled in `evmc_steppable_interpreter` 
And is returned in `GetTxContext()` instead of the one in `params`
This is an ugly fix needed because:
- when passing memory from Go to C, if it's a slice, you need to pin the memory, to insure it will note moved or deleted by Go's garbage collector.
- the problem is that (because they are different types), when calling `evmc_interpter.go:GetTxContext`, in there, it needs to translate from `vm.Hash` in `vm.Params` to `evmc.hash` defined type by `evmc`
- but this means that we cannot `unpin` the `evmc.hash` slice's memory (because it is returned to the C side)
- so we need to pin the `evmcBlobHashes` before calling `C.step_n_wrapper`,
This way we can …

CT: update evmc  for blobhash support

---

go/geth_adapter/adapter.go
go/vm/geth/geth.go

After the implementation of changes to Selfdestruct in Cancun in #556 and #557, it was decided that these changes should happen in the database. The right function is simply selected by checking the revision.

Update Selfdestruct EIP-6780

---

scripts/license/add_license_header.sh

This PRs modifies the add license script to ignore the `*/build/*` folders, which should anyways never be committed and should also be in the `.gitignore` file.

ignore build folders when checking for license

---

go/ct/gen/code.go
go/ct/gen/code_test.go
go/ct/gen/storage.go
go/ct/gen/storage_test.go
go/ct/spc/specification_test.go

This PR fixes some of the state generation issues that made the `TestSpecification_EachRuleProducesAMatchingTestCase` test randomly fail (depending on the state of the RNG). 
Also the `TestSpecification_SpecifiedRuleProducesMatchingTestCases` test is there to use iteratively in case any other rule fails as well, and to debug the generation. 
The 2 specific issues thar are solved in this changes are:
- limiting code size to be bigger than 2 if we are restrained by `isData` condition (if we need data there has to be at least one op followed by data)
- randomly setting an address as warm, but not "cleaning" it when "isStorageCold" condition is also present.
This PR fixes #550

CT: EachRuleProducesAMatchingTestCase flaky test

---

go/ct/spc/specification_test.go

This issue breaks our nightly CT test run since it introduces a race condition in the unit tests. It was introduced by #540 but seems to be unrelated to the change covered by this PR.

Fix race condition in EachRuleProducesAMatchingTestCase test

---

go/integration_test/processor/processor_test.go

While restructuring the directory structure, the processor test was moved into its own package without the needed import of the opera processor.

Enable testing of opera processor in integration tests

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/super_instructions.go

This PR removes functions that are not used (as shown by coverage test results) and moves super instructions to separate file, facilitating a more accurate coverage of the original set of instructions. 
The removed instructions (`noop`, `data` and `invalid`) are never reached because of an early filter in the interpreter using `NUM_EXECUTABLE_OPCODES`

LFVM: remove unused functions and move super instructions to own file

---

go/ct/rlz/parameters.go
go/ct/spc/specification.go

Coverage reported that there was no hit for the checks of jump/jumpi's destination overflow. 
This PR adds rules testing exactly that case.

CT: Add rules for jump over int32

---

go/ct/spc/specification.go

This PR improves the coverage of `EXTCODEHASH` rule by dividing the `preBerlin` rule into `warm` and `cold` cases, ensuring all branches are covered.

CT: extcodehash pre berlin

---

go/integration_test/processor/processor_test.go
go/integration_test/processor/scenario.go
go/integration_test/processor/scenario_test.go
go/integration_test/processor/world_state.go
go/integration_test/processor/world_state_test.go
go/tosca/interpreter_mock.go
go/tosca/processor_mock.go
go/tosca/types.go
go/tosca/world_state.go
go/tosca/world_state_mock.go

This PR introduces some infrastructure to simplify the definition of integration tests for [Processor](https://github.com/Fantom-foundation/Tosca/blob/93de631ba0e66082b1bb912c564fcb6637cfaa16/go/tosca/processor.go#L20) implementations.
In particular, the provided infrastructure enables the definition of test scenarios based on pre/post states and a transaction definition. During the test execution, the following steps are carried out:
- a transaction context containing the pre state is created
- the transaction is executed using the provided `Processor` implementation; state manipulations are tracked
- the final state after the transaction has been completed is compared with the expected state
- the receipt produced by the transaction is compared with the expected result
**Note to …

Improve processor testing infrastructure

---

go/ct/common/revisions.go
go/ct/rlz/conditions.go
go/ct/rlz/conditions_test.go
go/ct/rlz/domains.go
go/ct/rlz/expressions.go
go/ct/spc/specification.go

By adding the support for new revisions the number of generated test cases during a CT run increased to an unmanageable number. By evaluating the specification, conditions on read only mode, warm accounts and revisions could be changed. The number of test cases is reduced from 510.530.430.373 to 18.288.391.943 by these changes.

CT: Reduce number of produced test cases

---

go/ct/rlz/parameters.go
go/ct/spc/specification.go

This PR adds `math.MaxUint64` to `memoryOffsetForCopyParameterto` trigger overflow cases, in particular in `calldataload` rule

CT: expand `memoryOffsetForCopyParameter`

---

go/geth_adapter/adapter_test.go
go/integration_test/processor/processor_test.go
go/integration_test/processor/scenario_test.go
go/integration_test/processor/world_state_test.go
go/tosca/types.go
go/tosca/types_test.go

This PR changes the old `ValueFromUint64` to `NewValue`, keeping the old representation and decimal printing, but allowing the create a new value from up to 4 `uint64` much like `NewU256` 
This PR fixes #589

tosca: change `ValueFromUint64` to `NewValue`

---

go/ct/rlz/parameters.go
go/ct/spc/specification.go
go/interpreter/lfvm/ct.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/memory.go
go/interpreter/lfvm/super_instructions.go

This PR aims to improve coverage by including calls to `EnsureCapacity` in functions that need it to not fail.

LFVM: merge memory set/copy with EnsureCapacity

---

go/ct/st/memory.go
go/ct/st/memory_test.go

Thanks to the fuzzing experiments an unchecked overflow was found and fixed in LFVM memory expansion calculation function. 
This PRs add that fix in the analogous CT function and a corresponding test case that fails without this newly introduced check.

CT: Max Memory Size Check

---

.github/workflows/go.yml
go/ct/driver/probe.go

Vet is bundled with the go installation, no need for extra setup. This pass will run fast static checks for code sanity.
More about [Vet](https://pkg.go.dev/cmd/vet)
Vet is fast and can be run along the normal build script. Although it founds some trivial errors already, there is a second linter project that finds more interesting errors, and I would like to integrate it as an action as well: #608 
The bug found is a race condition: more about it here https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/
The choice of naming for the new variable is deliberate, this seems to be a convention to address this issue.

Add Go Vet pass to build action.

---

go/ct/gen/state.go
go/ct/rlz/domains.go
go/geth_adapter/adapter.go
go/integration_test/interpreter/instruction_info.go

This is part of the effort to enable #608 
Code removed was never used.

Remove unused code as reported by golangci-lint

---

go/ct/common/address.go
go/ct/common/bytes.go
go/ct/common/hash.go
go/ct/evm_fuzz_test.go
go/ct/gen/accounts_test.go
go/ct/gen/code.go
go/ct/gen/memory.go
go/ct/rlz/conditions_test.go
go/ct/spc/enumeration_test.go
go/ct/spc/specification_test.go
go/ct/st/accounts.go
go/interpreter/evmzero/evmzero_test.go
go/interpreter/geth/ct.go
go/interpreter/lfvm/hash_cache.go
go/interpreter/lfvm/instructions.go

The PR here either ignores or does error handling for the previously ignored functions, potentially returning errors.
- Rand (and hash), implement the read (and write) interfaces which are error typed, nevertheless these operations do not fail.
- Error handling is done in unit tests and benchmarks, benchmarks add a negligible constant overhead, and it is better to not benchmark failing functions.

Handle ignored error results discovered by static linter

---

go/integration_test/interpreter/instruction_info.go
go/interpreter/lfvm/converter.go

This PR changes the use of `geth.evm` codes for `tosca.opcodes` in `converter.go`
This PR dependes on #604

lfvm: remove geth dependency in lfvm opcodes

---

go/ct/common/address.go
go/ct/common/address_test.go
go/ct/gen/accounts.go
go/ct/gen/accounts_test.go
go/ct/gen/block_context.go
go/ct/gen/call_context.go
go/ct/gen/call_context_test.go
go/ct/gen/interval_solver_test.go
go/ct/utils/adapter_test.go
go/interpreter/geth/geth.go
go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instructions.go

The goal is still to enable #608
Three kinds:
- staticcheck detects range checks that are equal to type range. This is superfluous as the compiler already did that 
- deprecated calls, these are bigger than I. Are they really deprecated?  The code and the uses seem quite critical to me.

Handle errors discovered by static linter, staticcheck and ineffassign

---

go/ct/spc/specification_test.go

This test was disabled because it was generating timeouts in CI. Now that it's runtime has been reduced to under a minute, it should be fine to re-enable it. 
This PR fixes #615

SPC: re-enable Specification_NumberOfTestCasesMatchesRuleInfo

---

Makefile

This pr adds the `github.com/ethereum/go-ethereum/core/vm/...` packages to the coverage report of geth. This is the correction of an oversight. 
The resulting report accounts for coverage of all packages in both `./go/...` as well as `github.com/ethereum/go-ethereum/core/vm/...`, which would be created in an analogous place as before.

CT: fix makefile geth coverage command

---

.github/workflows/go-linter.yml
.gitignore
BUILD.md
Jenkinsfile

This PR enables go linting in PR CI.
Both [vet](https://pkg.go.dev/cmd/vet) and [staticcheck](https://staticcheck.dev/docs/) are to be satisficed before PRs are mergeable.

 Add Go linter to CI.

---

go/integration_test/processor/calls_test.go
go/integration_test/processor/examples_test.go

This PR adds an integration test stressing the maximal recursive call depth in a single transaction.
This test can also also be used to implement recursive calls in floria without the need of implementing different types of calls.

Add max depth integration test

---

BUILD.md
Jenkinsfile
Makefile
cpp/cmake/tosca_coverage.cmake
cpp/common/CMakeLists.txt
cpp/common/coverage/CMakeLists.txt
cpp/common/coverage/collect_coverage.c
docs/coverage.md
go/ct/common/cpp_coverage.go
go/ct/common/cpp_coverage_test.go
go/ct/driver/run.go

When running a C++ library from go, the coverage instrumentation is never dump to file and is lost. This process needs to be done manually in these cross-language environments.
The solution proposed loads a C library in the Go program, which exports the functionality to dump coverage data into files. This dumps coverage data for any loaded library in the program namespace with coverage enabled.

Add support for collecting C++ coverage data from Go processes

---

go/integration_test/processor/gas_billing_test.go
go/integration_test/processor/processor_gas_test.go
go/processor/floria/processor.go
go/processor/floria/processor_test.go

This PR implements gas refunding in Floria. Further, the gas integration tests are split into multiple functions and an end to end test for gas billing/handling using a mock interpreter is introduced. 
Fixes #575 and #603.

Floria: Implement gas refunding

---

go/integration_test/processor/calls_test.go
go/integration_test/processor/scenario.go
go/processor/floria/processor.go
go/processor/floria/run_context.go
go/processor/floria/run_context_test.go

One of the biggest differences between the different call types is whether they access the same storage. An integration test writing into storage and reading from the same slot in an inner call is added in this PR.
Some minor restructuring as preparation for the implementation in Floria is also performed.

Add integration test for different call types

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

This PR fixes the support for running the `geth` interpreter with the `aida` or `floria` processor in Aida.
The change in this PR prevents the `geth` reference interpreter maintained by Tosca to replace the `geth` interpreter implementation in a host system like Sonic or Aida. Before this change, the geth version included in the host system got replaced by a version with the following structure:
```
gethToToscaAdapter(toscaToGethAdapter(gethReferenceInterpreter)))
```
This is a surprising setup, that is not the expected configuration when users are selecting the `geth` VM option in Aida or Sonic.
The issue was not discovered earlier since the [RegisterInterpreterFactory](https://github.com/Fantom-foundation/go-ethereum-sonic/blob/2400937cc3b1c370ea8735d7af86eac621e4eb70/core/vm/tosca_integ …

Suppress export of geth reference interpreter to go-ethereum

---

go/integration_test/processor/create_test.go

This PR adds integration tests for CREATE and CREATE2 instructions. 
Due to the required setup of `initCode` and `toBeCreatedCode` the tests are rather long, to still keep them readable small numbers of lines is group and commented.

Integration tests for CREATE and CREATE2

---

.github/workflows/go.yml
.testcoverage.yml
Makefile
go/ct/common/hash.go

This PR adds a github workflow, a makefile target and a config file. These combined produce a report on the coverage and (when enabled) post this report on the PR.
This is currently disabled because the unit-test coverage of some packages does not meet the current requirements. This needs to be fixed in a separate PR or lowered thresholds. 
NOTE: 
a series of follow-up PRs will add unit tests to increase coverage and eventually empty the list of overrides

Github report coverage

---

.github/workflows/go.yml
Makefile

After merging the report coverage we observed that the tests were running 2 times for each commit and there was also a problem with the coverage report trying to publish in a PR when a commit was done into main (which has no PR). Also keeping into consideration that when developing it's easier to run just one command to get the report and not having to mentally record whether the `cover.out` is updated or not, we came up with this solution:
- for development one runs `make test-coverage` which will run the tests and then report the coverage on the updated code.
- for commits in PRs (aka branches that are not main) this is separated into 2 steps, `make tests-go` and `make coverage-report`
- for commits in main, this will only run `make tests-go`. 
Hence preventing commits in PRs to run …

Reorder makefile commands

---

go/integration_test/processor/create_test.go
go/integration_test/processor/processor_test.go
go/processor/floria/processor.go
go/processor/floria/processor_test.go
go/processor/floria/run_context.go
go/processor/floria/run_context_test.go

This PR adds support for CREATE and CREATE2 instructions to Floria. To ensure the right address is calculated another integration test is added, stressing this calculation.

Implement create calls

---

.testcoverage.yml
go/ct/rlz/conditions_test.go
go/ct/rlz/domains_test.go
go/ct/rlz/effect_test.go
go/ct/rlz/expressions.go
go/ct/rlz/expressions_test.go
go/ct/rlz/parameters_test.go

This PR adds UT to improve the coverage of the `rlz` package and removes it from the `override` config.
Some test have been deleted and refactored  together to make the most out of table testing.
Noteworthy comment:
coverage is not 100% because there are a couple of checks that can never fail but I think the should still not be removed, such as the inequalities in confitions_tests, or the `Op.Eval`. In both these cases the corresponding checks can not fail because the current implementations do no generate errors or allow values that could lead to the fail of those checks.

improve rlz coverage 

---

go/ct/driver/probe.go
go/ct/driver/run.go
go/ct/evm_test.go
go/integration_test/interpreter/integration_test.go

since we are installing the static check module with `@latest` whenever they release a new version we might get new findings. 
This is party good because we can keep improving our code quality, but it means that occasionally PRs will fail for reasons unrelated its changes.

Fix new linter findings

---

go/integration_test/processor/precompiled_test.go
go/integration_test/processor/scenario.go
go/interpreter/evmone/evmone.go
go/processor/floria/precompiled.go
go/processor/floria/precompiled_test.go
go/processor/floria/run_context.go
go/processor/test_utils.go

This PR adds support for precompiled contracts to Floria. 
Although unrelated but just a small fix, the newest supported revision of evmone is updated since the newly introduced tests have been failing. 
Fixes #576.

Floria: support for precompiled contracts

---

.github/workflows/rust.yaml

The existing script contains a superfluous `'`.

Fix github actions rust file syntax.

---

go/ct/evm_fuzz_test.go

Memory release was releasing a nil reference in scenarios that should be skipped.

Fix Differential fuzzing error found in nightly builds

---

.testcoverage.yml
go/interpreter/lfvm/ct.go
go/interpreter/lfvm/instruction_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go

This PR:
- adds tests for instruction `.String()` and code `.String()`
- removes unused error code `SEGMENTATION_FAULT`
- moves `switch` from `Run` that generates `tosca.Result` into its own function for ease of testing.
- adds tests for the multiple cases of `Run`
- adds tests checking for correct recording of statistics
- adds tests for statistics and logs printing.

LFVM: instruction & interpreter tests

---

go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/stack.go

This PR  removes remaining geth dependencies in lfvm by defining our own constants.
This PR fixes #410

LFVM: remove geth dependencies

---

go/interpreter/lfvm/hash_cache.go
go/interpreter/lfvm/instructions.go

This PR removes the context from the `hash_cache.hash` calls, and replaces the old `getHash` for corresponding calls to the new `keccak256` hash function. 
This PR contributes to #686

LFVM: remove context from hash cache

---

Jenkinsfile
go/interpreter/lfvm/converter_test.go

This PR adds a unit test running concurrent conversion steps on the code cache in an attempt to detect concurrency issues in the implementation. 
Such issues would be identified using Go's [data race detector](https://go.dev/doc/articles/race_detector) which is enabled using the `--race` when running tests. In order to detect such issues in PRs, a corresponding pass build step was added to the CI script running on Jenkins.

Add test case checking for a thread-safe code cache

---

go/ct/driver/cli/flags.go
go/ct/driver/run.go

Since CT runs nightly or every other night, we do not want to test for exactly the same set of states each run. To fix this issue, this PR changes the seed flag `Fetch` method, so that when `--seed` or `-s` are not set, it uses time as a seed. 
This PR fixes #707

CT: run uses random seed by default

---

go/interpreter/lfvm/converter.go
go/interpreter/lfvm/converter_test.go
go/interpreter/lfvm/ct.go
go/interpreter/lfvm/ct_test.go

This PR simplifies the implementation of PcMap's required by the CT adapter to translate between EVM and LFVM code positions. In particuluar:
- it eliminates the duplication of code conversion code in the `convert` function and the `genPcMap` function
- it eliminates a global variable retaining a cache for PcMap instances
- it replaces the maps used by the PcMap with slices
- it moves the PcMap code from the converter file to the CT file, since it is logically a part of the CT adapter
- it removes `error` return values in function signatures where only `nil` was returned

Simplify PC map in CT adapter

---

go/interpreter/lfvm/hash_cache.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/interpreter.go

This PR removes the hash instance retained in an execution context for hashing input data. After #685 has been added, this is no longer needed.

Remove hash buffer in LFVM context

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/ct_test.go
go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/lfvm.go
go/interpreter/lfvm/memory.go
go/interpreter/lfvm/stack.go

This PR fixes numerous code-style issues in the interpreter file without changing any functionality. The main elements are:
- naming for state constants and variables did not follow our general coding style guidelines
- types and constants had public visibility where it was not needed
- types have been found in identifier names, documentation, and comments
- flag names should be defined in the positive form (e.g. "noShaCache" => "withShaCache")

Fix code style issues in LFVM interpreter

---

go/interpreter/lfvm/converter_fuzz_test.go
go/interpreter/lfvm/instruction.go

Since the convert function accepts an unconstrained byte buffer coming from outside sources, the convert function is a good candidate for fuzzing, and increase resilience of the algorithm to invalid input.

Add Fuzzing function for lfvm opCodes convert function

---

go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instruction_statistcs_test.go
go/interpreter/lfvm/instruction_statistics.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/lfvm.go

This PR performs a clean-up pass on the interpreter implementation by
- cleaning up the interpreter `run` function signature by eliminating boolean flags and invalid flag combinations (e.g. logging and statistic can not be enabled at the same time)
- factoring out the instruction statistics run feature into its own file
- eliminating the global statistics instance; it is now associated to a VM instance
- rearranging code to fit a more logical order in the files
For the reviewers: this PR does not add or remove features; it is re-arranging code, which makes the diffs look quite convoluted; I would suggest to have a look at the new code structure by checking out this branch instead of solely focusing on the diffs.

Clean-up of LFVM interpreter infrastructure

---

go/integration_test/interpreter/integration_test.go
go/integration_test/interpreter/test_config.go
go/interpreter/lfvm/instruction_statistics.go

during integration testing, it was found that "lfvm-stat" panic when feed incorrect code (aka code that did not end in status `STOPPED`, `REVERTED`, `RETURNED`.
This case is made into a test to verify all variants handle this case properly without producing a panic, and fixed in `lfvm-stat`
This Fixes #650

LFVM: stats mode panics with non-terminal code

---

go/interpreter/lfvm/errors.go
go/interpreter/lfvm/gas.go
go/tosca/errors.go
go/tosca/errors_test.go

This PR moves `constErr` to `tosca`, so that it can be used in other projects as well, such as `floria` or `ct`.
Follow up PRs should take care of implementing the usage of this type and facilitating the comparison with `errors.Is`.
side note:
a similar approach can be taken for groups of errors that have a variable value, but for this a type needs to be made for each group of errors. We should be on the look to use this pattern since it simplifies error comparing

tosca: constErr 

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/ct_test.go
go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/stack.go
go/interpreter/lfvm/stack_test.go
go/interpreter/lfvm/super_instructions.go

This PR performs a clean-up pass over LFVM's stack implementation by
- fixing visibility
- aligning the naming of member functions (`Back` => `peekN`, `Data` => `get`)
- adding documentation
- adding unit test coverage
Note to reviewer: this PR does not cover the stack boundary infrastructure that happens to be located in the `stack.go` file but should be moved since it is much closer related to instructions than to the `stack`. This will be covered in a follow-up.

Clean up LFVM stack implementation

---

go/integration_test/processor/calls_test.go
go/integration_test/processor/create_test.go
go/processor/floria/run_context.go
go/processor/floria/run_context_test.go

This PR adds the checks whether an account exists or not to Floria.
By adding these checks in between precompiled contract handling and the interpreter call, several checks can be removed compared to the reference implementation.
Fixes #713.

Floria: Implement account exists check

---

go/interpreter/lfvm/hash_cache.go
go/interpreter/lfvm/hash_cache_test.go
go/interpreter/lfvm/instructions.go

This PR applies various cleanup steps of the LFVM hash cache implementation. In particular:
- refactoring the hash cache structure to use generic types to eliminate code duplication
- added documentation
- added unit tests for hashing, LRU caching order, and capacity constraints
- added micro-benchmarks to assess impact of code generalization
Benchmarks have been implemented and evaluated to assess the impact of those refactoring steps. The results are as follows:
```
pkg: github.com/Fantom-foundation/Tosca/go/interpreter/lfvm
cpu: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
│   base.txt   │              mod.txt               │
│    sec/op    │   sec/op     vs base               │
HashCache_Hits/size=16-4    517.1n ± 11%   482.8n ± 3%  -6.63% (p=0.001 n=10)
HashCache_Hits/size=32-4    36.73n …
```

Cleanup of the LFVM hash cache

---

go/integration_test/processor/create_test.go
go/processor/floria/run_context.go

Starting with the London revision, it is no longer possible to create accounts with a code starting with 0xEF. 
This simple check is added to Floria and checked with an integration test.

Floria: Invalid code starting with 0xEF is rejected

---

go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go

This PR eliminates redundant code from the LFVM interpreter loop. This cuts 4-11% of the execution time for dispatcher-intensive benchmarks like Fib.
```
goos: linux
goarch: amd64
pkg: github.com/Fantom-foundation/Tosca/go/integration_test/interpreter
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
│ baseline.txt │             modified.txt             │
│    sec/op    │    sec/op     vs base                │
Fib/10/lfvm-12       179.4µ ± 5%   160.7µ ±  5%  -10.45% (p=0.002 n=10)
Fib/10/lfvm-si-12    127.5µ ± 7%   116.0µ ± 10%   -9.04% (p=0.004 n=10)
geomean              151.3µ        136.5µ         -9.75%
```
```
goos: linux
goarch: amd64
pkg: github.com/Fantom-foundation/Tosca/go/integration_test/interpreter
cpu: Intel(R) Xeon(R) CPU @ 2.80GHz
│ baseline.txt │            modified.txt …
```

Cleanup of LFVM interpreter loop

---

go/integration_test/processor/access_list_test.go
go/integration_test/processor/scenario.go
go/processor/floria/precompiled.go
go/processor/floria/precompiled_test.go
go/processor/floria/processor.go
go/processor/floria/processor_test.go

This PR adds the access list introduced in the Berlin revision to Floria.
The integration test scenario had to been changed to also deal with keys. The current implementation requires an iteration through all (worst case) entries which is not performant but should not be a problem for the scenario, which is only used in tests.  
Contributes to #714.

Floria: Add access list

---

go/tosca/vm/opcodes.go
go/tosca/vm/opcodes_test.go

Replace string comparing function with something faster.
Unit test for the function already existed. 
Note: benchmark has been refactored, values here are still valid but factor 256 in each case.

 Refactor vm.OpCode IsValid 

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go

Some Instructions are not allowed in static contexts, such checks can be done per opcode basis instead of in the main dispatching function. 
Checks have been moved into each op execution routine, Call check (regarding zero value) was already in place.

Refactor allowed operations in static context check. 

---

go/integration_test/processor/create_test.go
go/processor/floria/processor.go
go/processor/floria/run_context.go

The Spurious Dragon revision introduced an upper bound for the resulting code size of a create instruction. This  check is added to the runContext of Floria and checked against geth using an integration test.
Contributes to #714.

Floria: Reject code longer than max code size

---

go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instruction_statistics.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/opcode.go
go/interpreter/lfvm/opcode_test.go
go/interpreter/lfvm/stack_usage.go
go/interpreter/lfvm/stack_usage_test.go

This proof-of-concept show-cases how re-defining op-codes as 9-bit values can help reduce complexity.
Advantages:
- simplifies code by not having to distinguish between no-valid, valid and executable OpCodes
- gets rid of code that was handling errors that can no longer be triggered
- eliminates implementation constants in the OpCode enum that signify certain boundaries in the OpCode number range

Switch to 9bit opcodes

---

rust/src/interpreter/mod.rs
rust/src/interpreter/run_result.rs
rust/src/interpreter/stack.rs
rust/src/interpreter/tx_context.rs

- add `ExecutionTxContext` (like `evmc::ExecutionTxContext` but with pointer and length fields converted to slices)
- add `RunResult`

Add ExecutionTxContext and RunResult

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/memory.go
go/interpreter/lfvm/memory_test.go

Memory internal functions should not be public.
This PR renames `ExpansionCost` into `getExpansionCost` and `Len` to `length`. 
This PR removes `Data` and `Print` methods, since print is never used and data had a single use that can be replaced by a call to `GetSlice`. 
Follow up PRs will make the other functions in memory private and add tests for them.

LFVM: memory methods rename part 1

---

go/interpreter/lfvm/instructions_test.go

This PR fixes a lack of stack-value initialization in the test `TestCreateShanghaiInitCodeSize`.
The test assumed implicitly that a newly created stack is filled with zeros. However, due to stack-recycling, this is not the case. The content is actually undefined. This lead the given test to be flaky, since one of the stack values assumed to be zero leads the following issue if it is not zero:
```
--- FAIL: TestCreateShanghaiDeploymentCost (0.00s)
instructions.go:888: Unexpected call to *tosca.MockRunContext.GetBalance([0x0100000000000000000000000000000000000000]) at /home/herbert/coding/fantom/tosca/go/interpreter/lfvm/instructions.go:888 because: there are no expected calls of the method "GetBalance" for that receiver
controller.go:98: missing call(s) to *tosca.MockRunContext.Call(is …
```

Zero-initialize stack values in init code size test

---

Jenkinsfile
go/ct/driver/run.go
go/lib/cpp/coverage.go
go/lib/cpp/coverage_test.go

Right now, the LFVM implementation has dependencies to various CT packages. Among those, the `ct/common` package, which, before this PR, has a dependency to C++ code.
In order to build the LFVM interpreter as part of the Go sonic client without the need of an extra C++ compilation step, this dependency needs to be resolved. 
In the long run, all CT dependencies should be eliminated from the LFVM. However, this requires more work. To unblock the build development process in the meanwhile, the C++ coverage utility is factored out into its own `cpp` package, where it also conceptionally fits better.

Move C++ coverage utility from ct/common to lib/cpp

---

go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

This PR removes the function `addressInAccessList` and reworks its functionality into `getAccessCost`. It also adds comprehensive documentation for the values used, and a test for the different cases.
Note: static call prices after berlin should be 0, and warm cost should be applied in dynamic cost calcualtion (https://eips.ethereum.org/EIPS/eip-2929). This changes are also applied in this PR.

LFVM: move `addressInAccessList` to `getAccessCost`

---

go/integration_test/interpreter/integration_test.go
go/integration_test/interpreter/invalid_code_test.go
go/integration_test/interpreter/invalid_instructions_test.go
go/integration_test/interpreter/revision_test.go
go/integration_test/interpreter/stack_boundary_test.go
go/integration_test/interpreter/test_config.go
go/integration_test/interpreter/test_config_test.go
go/integration_test/interpreter/verify_gas_test.go
go/integration_test/interpreter/vm_test.go
go/interpreter/lfvm/lfvm.go
go/interpreter/lfvm/lfvm_test.go

This PR restricts the default registration of LFVM interpreter configurations to the `lfvm` and `lfvm-si` configurations. These are the only configurations currently accessed outside Tosca. In a follow-up step, this set is to be further restricted to the `lfvm` option only (once down-stream projects have been updated).
Some changes contributed by this PR:
- split of the officially supported configurations and experimental configurations
- renamed the LFVM `VM` type to `lfvm` to make the implementation package private
- updated integration tests to automatically cover all registered interpreter implementations with the exception of logging configurations to ease the diagnosis of failing unit tests (eliminate command line pollution)

Split official LFVM configuration and experimental configurations

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go
go/integration_test/interpreter/revision_test.go
go/integration_test/interpreter/test_evm.go
go/integration_test/interpreter/vm_test.go
go/integration_test/processor/processor_test.go
go/interpreter/evmone/evmone.go
go/interpreter/evmone/evmone_test.go
go/interpreter/evmzero/evmzero.go
go/interpreter/evmzero/evmzero_test.go
go/interpreter/geth/geth.go
go/interpreter/lfvm/lfvm.go
go/interpreter/lfvm/lfvm_test.go
go/tosca/interpreter_registry.go
go/tosca/interpreter_registry_test.go

This PR updates the interpreter registry to contain factories instead of instantiated interpreters. This provides the following benefits:
- EVM configurations do not consume resources if they are not used
- when creating an EVM, client-code defined properties (e.g. cache sizes) can be passed the construction process of the interpreter instances (prepared but not implemented by this PR)
**Note to reviewers:** start with the changes in the Tosca package, which is the main part of this PR. All the rest is just API adaptations.
TODO:

Replace interpreter instances with interpreter factories in registry

---

go/interpreter/lfvm/instruction_statistcs_test.go
go/interpreter/lfvm/lfvm.go
go/interpreter/lfvm/lfvm_test.go

This PR performs a clean-up of the LFVM instantiation code. It does so by
- providing a new `NewInterpreter(Config)` function where `Config` is supposed to be extended in the future with LFVM specific properties (e.g. cache sizes); the implementation of these properties is beyond the scope of this PR, but since this interface will be accessed by down-stream components (e.g. the Sonic client), adding the `Config` only once needed will be a breaking change;
- the package internal pre-existing `Config` was made private
- the old factory function `NewVm` was made private
This is part of #676, #687, #774, and #766

Provide public LFVM interpreter creator function

---

go/interpreter/lfvm/converter.go
go/interpreter/lfvm/converter_test.go

While looking through the converter code it was noticed that the check for the maximum PC supported by the PC instruction conversion was off by one.

Fix off-by-one check in converting PC instructions

---

go/interpreter/lfvm/instructions.go

`CREATE` and `CREATE2` are two extremely similar operations with a little variations for the latter.
This PR unifies their implementation making maintainability a little bit easier for the future (and also bugfixing if ever needed) and reducing code duplication.

LFVM: unify create and create2

---

go/interpreter/lfvm/instructions.go

We want to move towards the memory methods being secure (aka only modifying the memory once it has been expanded and charged for). But there were the exception cases in the call operations, where we needed to know how much the memory expansion would cost before using it.
This PR moves up the memory expansions within the `genericCall` function keeping a reference for the return slice, hence removing the need of a custom read/write of memory that would not expand it. 
CT run for the calls was executed and passed.

LFVM: `genericCall` memory expansion

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/memory.go
go/interpreter/lfvm/super_instructions.go

Different error status were handled similarly but inconsistently. Functions were also inconsistent when propagating or generating errors regarding when they would be responsible for reporting `statusError`, because of this there were also a lot of code smells of the type 
```
if err != nil {
return
}
```
Hiding error handling which seems very error prone.
This PR:
- unifies the 3 erroneous status (`statusOutOfGas`, `statusInvalidInstruction` and `statusError`) in a single `statusError`
- adds documentation for functions whose errors should be handled by caller
- consistently handles error propagating and handling.
A CT run was made to corroborate that correctness of known cases has not been affected.

LFVM: unify error status

---

go/interpreter/lfvm/converter.go
go/interpreter/lfvm/converter_fuzz_test.go
go/interpreter/lfvm/converter_test.go
go/interpreter/lfvm/instruction.go
go/interpreter/lfvm/opcode.go
go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/353ba911ad2dc191
go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/6e0463cbdc2d559f
go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/8b15f710f79d31dd
go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/c94ac12daf9859fd

This PR adds unit tests for the following code conversion properties:
- all JUMPDEST instructions remain at the same position as in the input code
- base instructions are converted to their corresponding LFVM instruction if super instructions are disabled
- push operations are encoded and automatically zero-padded to their full length
- all JUMP_TO instructions point to their immediate JUMPDEST successor
- super instructions are ignored if disabled
- super instructions are identified if enabled
The PR also strengthens the checks covered by the code conversion fuzzer.
By reviewing the tests the following bug was identified:
- the size of codes in cache was computed assuming each instruction only takes 1 byte; actually it takes 4

Add unit tests for code conversion

---

go/interpreter/lfvm/errors.go
go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/memory.go

`useGas` used to return `bool`, to inform whether it was successful or not, in Go this should be done using `error`, for error propagation. 
This PR does just that, changes the return type from `bool` to `error` and checks whether this error is nil or not in all the call places. 
This PR should be carefully rebased with #772 since they are both about errors, but this change seemed big enough, conceptually, to be its own PR.

LFVM: change return type of useGas to error

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/errors.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/memory.go
go/interpreter/lfvm/memory_test.go
go/interpreter/lfvm/super_instructions.go

The purpose of this PR is to facilitate the tasks in #684 and #751, by returning explicit errors that remain unobscured (not overwritten or somehow interpreted) that can be tested against. 
The main change is the removal of the stateful function `signalError` and replace it with a stateless error return mechanism. This is idiomatic, as every error-prone situation will be handled with the `if err := expr; err != nil { return err }` pattern. 
- Missing returns after 'c.signalError'  are not possible any more. 
- Overwrites of errors because of calling `c.signalError` are not possible any more. 
Early prototyping detected some issues that were missed because of funnelling errors through the same `statusError`category   
- MStore cannot produce static mode violations, nevertheless it is …

LFVM, Refactor error propagation in interpreter: ops return errors

---

.github/workflows/go-linter.yml
.github/workflows/go.yml
Jenkinsfile
Makefile
go/integration_test/interpreter/test_config.go
go/interpreter/evmone/evmone.go
go/interpreter/evmzero/evmzero.go
go/interpreter/evmzero/evmzero_test.go
go/interpreter/geth/geth.go
go/interpreter/lfvm/instruction_statistcs_test.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/keccak.go
go/interpreter/lfvm/lfvm.go
go/lib/cpp/coverage_test.go
go/tosca/interpreter_registry.go

This PR makes more difficult to ignore error returns. 
The problem why this was not working earlier is explained [here](https://www.dolthub.com/blog/2024-07-24-static-analysis/)
Found cases have been fixed with usual methods. 
Only the close call, between an error generation and its use, seems odd. This error in particular is discussed in the [go-PR](https://github.com/golang/go/issues/20148#issuecomment-2148205291) that attempted to enable this check in vet but was rejected.

Add new linter to detect unassigned error returns

---

go.mod
go.sum
go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go
go/integration_test/processor/processor_test.go
go/processor/opera/processor.go

As a preparation for the integration of Tosca into Sonic, the Tosca extensions in the [go-ethereum-sonic](https://github.com/Fantom-foundation/go-ethereum-sonic) repository got [revised](https://github.com/Fantom-foundation/go-ethereum-sonic/pull/4). This PR updates the dependency to to the latest version and applies necessary interface adaptations.
The interpreter registry in `go-ethereum-sonic` was eliminated by [#4](https://github.com/Fantom-foundation/go-ethereum-sonic/pull/4). As a consequence, the geth registry management code can be eliminated from the `geth_adaptor`, as covered by this PR.
This PR also eliminates the dependency between the `geth_adapter` package and specific interpreter implementations. Before this PR, by importing the `geth_adapter` the `lfvm`, `evmzero`, and …

Update go-ethereum-sonic dependency

---

rust/src/ffi/evmc_vm.rs
rust/src/ffi/steppable_evmc_vm.rs
rust/src/interpreter.rs
rust/src/types/amount.rs
rust/src/types/code_reader.rs
rust/src/types/opcode.rs
rust/src/utils/gas.rs

- add `u256::try_into_u64`
- call `code_reader.next()` after Opcode match
- do not check if address is sender or coinbase address

Evmrs refactor

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

the previous `checkInitCodeSize` also did modifications to gas, which was not documented nor in the function name. Since we trying to maintain all `useGas` calls in `opX` functions, this is moved to `genericCreate` along with the revision check, simplifying greatly this function.

LFVM: refactor max init code size check

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/interpreter.rs
rust/src/types/execution_context.rs
rust/src/types/mock_execution_message.rs
rust/src/types/mod.rs
rust/src/utils/gas.rs
rust/src/utils/helpers.rs

- add trait `ExecutionContextTrait` in order to mock `ExecutionContext`
- make all functions which took `ExecutionContext` as an argument generic over `ExecutionContextTrait`
- add `MockExecutionMessage`
- (partially) test `Interpreter::run`

evmrs: Test Interpreter::run

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/ct_test.go
go/interpreter/lfvm/instruction_statistcs_test.go
go/interpreter/lfvm/instruction_statistics.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go

This refactor facilitates #684 
The change removes `context.status` and `statusError` in favor of a `(status, error)` return type for the complete execution of the lfvm.
- A extra change in the interpreter was needed to correct program counter position after error. This was not a problem in main so far because `statusError` was returned. Since it does not exist anymore, the program counter was read at the wrong position. 
- Benchmarks have been reordered, to follow order of relevance. 
The most delicate change is in [go/interpreter/lfvm/ct.go](https://github.com/Fantom-foundation/Tosca/pull/795/files#diff-8732597f25fb78bbf7cc4df47e41abef29441a1e8690763ea444bc4c37c15f45), where the (status, error) pair needs to be converted into (*st.State, error). This has a semantic difference because …

LFVM: Refactor Run method to return tuple (status, error)

---

rust/src/evmc.rs
rust/src/ffi/evmc_vm.rs
rust/src/interpreter.rs
rust/src/types/amount.rs
rust/src/types/memory.rs
rust/src/types/stack.rs
rust/src/utils/gas.rs
rust/src/utils/helpers.rs

- remove two unsafe blocks and replace them with code which looks like it allocated but (at least in compiler explorer) is optimized away
- switch parameter order of `consume_gas` for better readability and consistency
- add `Gas` struct and make all functions in gas.rs methods of `Gas`
- add (more) tests for memory, stack, gas and helpers

evmrs: add tests and remove some unsafe code

---

rust/Cargo.lock
rust/Cargo.toml
rust/driver/Cargo.toml
rust/driver/src/host_interface.rs
rust/driver/src/lib.rs
rust/src/interpreter.rs
rust/src/lib.rs
rust/src/types/execution_context.rs
rust/src/types/mock_execution_message.rs
rust/src/types/mod.rs

Add `driver` crate. This crate calls `evmrs` via the C FFI interface. It will be used for integration testing and for benchmarks.

rustrs: Add rust driver crate

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go

In evm.codes it states that both `RETURN` and `REVERT` much charge for the memory expansion cost. However in our previous implementation this was done as part of getting the data from the context to build the `tosca.Result` at the end of a `run`. 
This PR:
- moves that memory expansion into the corresponding operation implementations, adding a function for the common parts and testing it. 
- CT conversion used to rely on a previous function called `getOutput` to also get the `ReturnData`, this now has it's own implementation.

LFVM: Return/Revert

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/interpreter_test.go

part of #684
This PR adds a unit test to check that every opcode can get dispatched by the interpreter. 
Every opcode gets a context where they can sucessfuly execute. The interpreter will dispatch the opCode to the appropiate handling function. 
Note: 
This change removes an old test, because of the change of paradigm, we are testing properties and not the bulk on instructions here. The one single problem is that the test for STORE and SLOAD will be deleted and such instructions are not yet tested. A plan to test WARM/COLD instructions is in the making here #751

LFVM: Test interpreter dispatcher

---

go/interpreter/lfvm/interpreter_test.go

Previously the test `TestRunReturnsEmptyResultOnEmptyCode` only checked that an empty code did not produce output, consumed gas and it was a successful execution. This test is expanded to check that all terminating operations and successful terminating conditions are handled properly, 
This PR contributes to #684

LFVM: successfully terminating code execution

---

go/interpreter/lfvm/gas.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

Part of #751
This PR fixes and tests many of the changes introduced in EIP-2929 (https://eips.ethereum.org/EIPS/eip-2929) :
- Fixes static costs of BALANCE, EXTCODECOPY, EXTCODESIZE and EXTCODEHASH to zero. All gas for these operations should be dynamically calculated. 
- removes `gasEip2929AccountCheck` because it was duplicated functionality from `getAccessCost`, which is already tested.
- adds test checking for the extra charging of warm/cold accesses in Berlin and after, in the relevant opeations.
NOTE: SelfDestruct is a special case and has its own pre-existing tests.

LFVM: test EIP2929 warm/cold acceses charging

---

go/geth_adapter/adapter_test.go

The geth adapter is used to make Tosca's Interpreters available inside of geth. Unit tests for this code have been added in this PR. Since the majority of functions are just forwarding calls to the geth state db, mocking is used to ensure that arguments are forwarded correctly.
Contributes to #725.

Add geth adapter tests

---

go/interpreter/lfvm/lfvm.go

This PR removes the super-instruction version from the list of officially supported versions and adds it to the experimental configuration set.
This is part of #687

LFVM: make super-instruction configuration experimental

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/memory.go
go/interpreter/lfvm/memory_test.go
go/interpreter/lfvm/super_instructions.go

This PR is part of a series of PRs that aim to make private and improve the memory methods. 
In this PR:
- `SetByte` and `SetWord` are now private functions.
- `Set` functions is removed since we are moving towards enforcing that memory can not attempt to read/write without expanding first.
- `SetWithCapacityAndGasCheck` is renamed to `set`, simplified to simply call `getSlice` from #761 and then copy from input value to the slice.
- `setByte` and `setWord` is implemented as a specialization of `setWithCapacityAndGasCheck`.
- tests are added for `set`, `setByte` and `setWord`.
This is part of #682
This PR will rework set to be a specialization+copy of `getSlice` from #761

LFVM: `set` and `setByte` test

---

.github/workflows/rust.yaml

This PR runs all rust related ci steps (except for cargo machete which does not support this) with the feature powerset. This in preparation for optimizations which will be put behind features to make sure each combination works.

evmrs: test feature powerset in ci

---

rust/Cargo.lock
rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/benchmarks/benches/interpreter.rs
rust/benchmarks/src/lib.rs
rust/benchmarks/src/main.rs
rust/driver/src/lib.rs
rust/src/lib.rs
rust/src/types/mock_execution_message.rs
rust/src/types/mod.rs
rust/tests/ffi.rs

This PR adds the `benchmarks` which contains benchmarks (currently only `ffi_overhead`) for calling from Rust via FFI into evmrs.
The benchmarks can be used in two ways:
- with criterion to compare different features:
`cargo bench --package benchmarks --profile profiling [--features <feature1>,<feature2>,...]`
- as a standalone executable for profiling
`cargo build --package benchmarks --profile profiling [--features <feature1>,<feature2>,...]`
then use `./target/profiling/benchmarks` with the profiler of your choice

evmrs: add benchmarks

---

.github/workflows/rust.yaml

- fix rust-cache action: because there is no `Cargo.toml` in the root it always failed. With an explicit path to the workspace it should now hopefully work.
- add rust-cache action to all jobs
- run clippy also work benchmarks

evmrs: fix&improve ci

---

rust/benchmarks/benches/interpreter.rs
rust/benchmarks/src/lib.rs
rust/benchmarks/src/main.rs
rust/driver/src/lib.rs
rust/src/ffi/evmc_vm.rs
rust/src/ffi/steppable_evmc_vm.rs
rust/tests/ffi.rs

This PR adds `Instance` and `SteppableInstance` in the driver lib and makes all `run*` functions methods of those structs. They both call the respective create function in their constructor (`Default` impl) and the destroy function in their `Drop` impl.
In the benchmark lib `RunArgs` now have a field of type `Instance`. Therefore it is no longer necessary to call the create function in each benchmark iteration but instead only once, which more closely resembles how `evmrs` would be used.
Additionally `evmc_create_steppable_evmrs` and `evmc_create_evmrs` not return mutable pointers which should have been the case all along.

evmrs: create vm instance only once in driver

---

go/interpreter/lfvm/interpreter_test.go

part of #751
Although this test affects the domain of the instructions, it is straight forward to implement it in the interpreter dispatcher, to avoid having to call the appropriate instruction callbacks.

LFVM: Test execution of instructions before they are introduced

---

go/interpreter/lfvm/gas.go
go/interpreter/lfvm/gas_test.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

To ensure that each early returned is behaving as expected, we test it.
This PR adds:
- test for `checkSizeOffsetUint64Overflow` all 4 cases.
- removes `checkGas` from `genericCall` and replaces it for calls to `c.useGas` this way we do not need to check for overflow when adding each expense. 
- inlines function `CallGas`  and removes its test.
- adds a test for all the error cases of `genericCall`
- adds test for static context propagation
- adds test for internal call result propagation in the stack

LFVM: genericCall errors test

---

go/interpreter/lfvm/instructions_test.go

During the refactor of self destruct gas checking, no test checking out of gas was introduced, this PR fixes that.

LFVM: selfdestruct out of gas check

---

go/ct/driver/run.go

This PR adds a temporary fix for the failed cases when the PC points to data, founded in #660.
In the future, this should not be ignored in the runner but rather the specification rule should be updated.

CT: Temporary fix for PC on data

---

go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go

The normal handling of stop conditions in the VM is to return an error and stop execution. Errors triggered by the VM are equally critical and results on all the gas being consumed. There is no reason to consume the gas for Out of gas scenarios but not for any of the other stopping conditions, therefore this logic is somewhere else and doing it at this point in execution is redundant and error-prone.
The real place where gas gets consumed is [here](https://github.com/Fantom-foundation/Tosca/blob/db1b6de32735886de9f8e7796f5830ddb27f3229/go/interpreter/lfvm/interpreter.go#L115)

LFVM: Remove use of gas on use gas failure.

---

go/interpreter/lfvm/instructions_test.go

part of #751 
This test adds coverage for simple instructions with internal control flow. 
Add test for:
- isZero
- less/greater than
- signed less/greater than
- shift right/left
- signed arithmetic right shift

LFVM: add test for operations with internal control flow

---

go/interpreter/lfvm/instruction_logger.go
go/interpreter/lfvm/instruction_logger_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/lfvm.go

We want to add the flexibility of choosing whether logging should be done to a file or stdout/err.
For this we change the `loggerRunner` to take an `io.Writter` and log in there. If no writter is provided then nothing will be logged.

LFVM: refactor loggerRunner to accept io.Writer instead of printing to stdout. 

---

.gitignore
rust/.gitignore
rust/BUILD.md
rust/scripts/bench.sh
rust/scripts/compare-features.sh
rust/scripts/coverage.sh
rust/scripts/test.sh

This PR changes bench.sh such that it accepts a list of feature sets for evmrs to run the Go VM benchmarks and documents how to use this script in BUILD.md

evmrs: pass feature sets to bench.sh and document usage in BUILD.md

---

go/interpreter/lfvm/instruction_statistcs_test.go
go/interpreter/lfvm/instruction_statistics.go

This PR adds test to check that:
- when we try to record statistics, if there is no `statistics` record, one will be created
- when the record has more than X entries, and there is a call to `getTopN(record, X)`, only the X instructions with the most entries will be shown.

LFVM: add tests for statistics runner

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

Part of #751 
Simplify function and test branches.
The reason behind multiple inputs for each case is that when `requestedBlockNumber` overflows, is still an out of range case.

LFVM: Add test for BLOCKHASH history logic

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/ct_test.go
go/interpreter/lfvm/instruction_logger.go
go/interpreter/lfvm/instruction_logger_test.go
go/interpreter/lfvm/instruction_statistics.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go

This is a minimal change that addresses the problem detected in #818. 
The issue being the impossibility to differentiate logical errors (execution violations, program errors) that turn into a failed but still valid execution from runtime errors that are outside from the domain of valid executions (namely the possibility of not being able to write into the file when logging an execution) 
This PR is intentional minimal because there are many helper tools inside the VM using errors to flag execution violations and the error type is the most convenient way to do such. 
alternatives considered were:
- use an enum type for VM logical errors: this would have needed a successful default value and replace all the comparisons `!= nul` with `!= Ok`, Changes would be large, code will be verbose, …

LFVM Differentiate logic errors from execution errors

---

go/interpreter/lfvm/interpreter_test.go

part of #751 
Remove all mocks of run-context deprecated functions, test fails if any is used.

LFVM: Test use of deprecated functions, none allowed

---

.testcoverage.yml
go/interpreter/lfvm/ct.go
go/interpreter/lfvm/memory.go
go/interpreter/lfvm/memory_test.go

Part of #751 
Later refactors in instruction handling made apparent that `expandWithoutChargingGas` could never return an error. 
This PR refactors the process of computing costs and expanding the memory to remove dead code (error handling branches of redundant error checks).
The computation of cost expansion and valid word size are fused into a single function because the two computations are closely related to each other and produce errors with the same inputs. This lead to one of the two functions shadowing the error handling of the other and rendering dead code.

LFVM: refactor memory expansion to improve testability.

---

go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/353ba911ad2dc191
go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/6e0463cbdc2d559f
go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/8b15f710f79d31dd
go/interpreter/lfvm/testdata/fuzz/FuzzLfvmConverter/c94ac12daf9859fd

This data was accidentally added by #784.

Remove accidentally committed fuzzing test data

---

go/interpreter/lfvm/instructions.go

EIP150 states that only 63/64 of the available gas can be passed on to the recursive calls. This creates a case of a gas consumption that can never fail, and this resulted in a branch of dead code that could never be triggered. To remove this, in this PR, I remove the call to `useGas` and replace it for a direct operation to the context's gas.
This solutions comes from this (https://github.com/Fantom-foundation/Tosca/pull/837#discussion_r1789716178) discussion. 
This solution passes:

LFVM: genericCall eip150 consume

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter.go

part of #751 
This PR adds tests for `genericCreate`:
- In all error cases, out of gas due to different checks depending on revision and create kind.
- ensuring result of creation is properly saved in stack

LFVM: genericCreate tests 

---

go/interpreter/lfvm/instructions_test.go

This PR is part of #751
This PR adds 2 test, one for out of gas and one for the regular usage of `opExp`.

LFVM: opExp test

---

go/interpreter/lfvm/instructions_test.go

Part of #751 
Adds 2 tests, one checking out of gas scenarios, another checking the same hash produced regardless of using hash cache or not.

lfvm: sha3 tests

---

go/interpreter/lfvm/instructions_test.go

This PR is part of #751 
add test for successful case of `extCodeHash` and check that the correct hash is written in the stack.

LFVM: extcodehash test

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

part of #751 
Add tests for log operation. The test regarding minimum version is done in together with all operations introduced in different revisions.

LFVM: Add test for log operation

---

rust/Cargo.lock
rust/Cargo.toml
rust/scripts/bench.sh
rust/src/interpreter.rs
rust/src/types/amount.rs
rust/src/types/code_reader.rs
rust/src/types/memory.rs
rust/src/types/mock_execution_message.rs

- bump deps (in particular `evmc-vm` which now has a `code_hash` field in `ExecutionMessage`)
- when creating an `u256` from bytes do not create `[u8; 32]` first and then convert into u256 but create u256 directly and use DerefMut impl
- cd into output dir and invoke benchstat there. this avoids having the full path in the header of the table which benchstat generates which blows up the table width

evmrs: bump deps & refactor

---

go/interpreter/lfvm/instructions_test.go

part of #751 
Old test is replaced with new ones:
- min version is tested for all ops in "TestInterpreter_InstructionsFailWhenExecutedInRevisionsEarlierThanIntroducedIn" 
- memory expansion is tested in memory tests.
- add overlapping range test
- test for errors happening both on read and write. 
- test gas cost for word count.

LFVM: Add test for mcopy

---

go/examples/static_overhead.go
go/integration_test/interpreter/vm_test.go

This PR adds the `BenchmarkStaticOverhead` benchmark. This benchmark tries to represent the worst case for very short contracts. In particular, it tries to trigger all allocations that happen when using an evmc interpreter, which, depending on how it is implemented, may need to copy data into new allocations.

Add static overhead benchmark

---

go/interpreter/lfvm/instructions_test.go

part of #751 
This pr adds tests to check parameters passed to context calls for `GetCode`  and  `GetCodeSize`

LFVM: Add tests for code related context calls

---

go/interpreter/lfvm/instructions_test.go

part of #751 
This pr adds a test to check arguments passed to storage calls.

LFVM: add test to validate storage runtime context calls arguments. 

---

.testcoverage.yml
go/interpreter/lfvm/converter_test.go

Part of #751 
Refactor introduced a new branch, this pr adds a test for the situation where converter does not find any SI fit for the input and it falls-back to use normal LFVM instructions.

LFVM: add test to bring converter coverage back to 100%

---

go/interpreter/lfvm/ct.go
go/interpreter/lfvm/ct_test.go

This pr refines CT to reduce need for testing. 
- First, use the sanctioned constructor for the LFVM to get the converter from. This removes the risk of testing a different configuration in CT than the production code
- Manually increase memory size and cost of expansion, since this expansion cannot produce errors
- remove error in status convert, statusFailed is sufficient for the CT to figure out that something did not work out.

LFVM: comments to #869

---

rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/types/code_reader.rs
rust/src/types/memory.rs
rust/src/types/mod.rs
rust/src/types/stack.rs
rust/src/types/status_code.rs
rust/src/utils/gas.rs
rust/src/utils/helpers.rs

This PR extracts all opcode implementations into functions. This in in preparation for other function dispatch approaches, in particular to be able to use a jump table.

evmrs: create functions for each opcode impl

---

go/interpreter/lfvm/super_instructions_test.go

Part of #751
Although SI is not part of the release scope, adding a test for this file sets coverage to 100% for the super-instructions file.
This facilitates threshold for the complete LFVM

LFVM-SI: add test for  od dup2_lt

---

rust/Cargo.lock
rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/lib.rs

This PR adds the feature "mimalloc". When enabled the default memory allocator is replaced by mimalloc.

evmrs: add feature "mimalloc"

---

rust/Cargo.lock
rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/benchmarks/src/lib.rs
rust/driver/Cargo.toml
rust/driver/src/host_interface.rs
rust/driver/src/lib.rs
rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/lib.rs
rust/src/types/execution_context.rs
rust/src/types/mock_execution_message.rs
rust/src/utils/helpers.rs
rust/tests/ffi.rs

This PR adds the feature "custom-evmc". When this feature is enabled a different version of evmc-vm is used, in which multiple allocations are avoided. 
To simplify the imports, evmrs (lib) reexports evmc_vm.
Important changes:
- evmrs reexports evmc_vm
- because ExecutionMessage now holds slices instead of Vec it has a lifetime
- output is now Option<Box<[u8]>> instead of Option<Vec<u8>>
- Interpreter -> ExecutionResult conversion now need a &mut because it moves the output field out of it leaving None behind

evmrs: add feature "custom-evmc"

---

rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/interpreter.rs

This PR adds the feature "jumptable". When enabled, opcode dispatch is done using a jumptable instead of a switch.
Changes:
- add type alias OpResult and OpFn
- remove match in Interpreter::run and call Interpreter::run_op instead
- add two Interpreter::run_op impls, one using switch and one using the jumptable

evmrs: add feature "jumptable"

---

rust/Cargo.lock
rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/interpreter.rs
rust/src/types/hash_cache.rs
rust/src/types/mod.rs

This PR adds the feature "hash-cache". When enabled, the sha3 hashes of 32 and 64 byte slices are stored in an last-recently-used cache.

evmrs: add feature "hash-cache"

---

.github/workflows/rust.yaml

This PR removes the features mock, dump-cov and performance from feature matrix testing in CI.
With every feature the size of the feature matrix doubles so now that more and more features are added it is essential to only test those combinations that really matter.
Feature performance is just a combination of other features and is therefore already tested implicitly.
Feature mock is enabled for tests do it is also enabled implicitly.
Feature dump-cov is completely independent from all other features and also just contains two lines of code.

evmrs: exclude mock,dump-cov,performance from feature matrix testing

---

.testcoverage.yml
go/ct/utils/adapter.go

This was discovered by running coverage of lfvm Ct runs. CodeHash was never filled.

CT: Add CodeHash for CT runs

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

Running the ethereum tests, multiple tests stressing the SELFDESTRUCT were failing. The account should always be selfdestructed but only return true for the first time.

Fix selfdestruct in geth adapter

---

.testcoverage.yml
go/interpreter/lfvm/lfvm.go
go/interpreter/lfvm/lfvm_interface_test.go
go/interpreter/lfvm/lfvm_test.go
go/tosca/interpreter.go

part of #684 
This PR adds testing for lfvm.go, in particular to registration of the experimental configurations of the vm and error handling during execution or construction of the vm.

LFVM: Rest register experimental features into global registry

---

go/integration_test/interpreter/dynamic_gas.go
go/integration_test/interpreter/verify_gas_test.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter_test.go

The ethereum tests pointed out another problem regarding selfdestruct, the dynamic gas computation should not rely on whether the account exists but if its balance = 0, code = nil and nonce = 0.

Fix selfdestruct empty vs. exists bug

---

.testcoverage.yml
go/interpreter/lfvm/ct.go
go/interpreter/lfvm/ct_test.go
go/interpreter/lfvm/instruction_logger_test.go
go/interpreter/lfvm/instruction_statistcs_test.go
go/interpreter/lfvm/interpreter.go
go/interpreter/lfvm/interpreter_test.go
go/interpreter/lfvm/lfvm.go

This PR is part of #751 
This PR adds tests for CT adapter.
Early tests shown that CT was running with sha3 cache disabled, this pr forces CT runs to use the sanctioned configuration for the release.

LFVM: CT Adapter tests

---

.testcoverage.yml
Makefile

This PR sets the requirement for 100% coverage for the LFVM. 
Additionally, rewrites ct coverage tool to collect coverage of the LFVM code only, speeding up the process.

LFVM: 100% coverage :pizza: 

---

rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/types/cache.rs
rust/src/types/hash_cache.rs
rust/src/types/jump_analysis.rs
rust/src/types/mod.rs

This PR add the feature "thread-local-cache". When enabled, all enabled caches (jump cache or hash cache or both) will use a thread local cache instead of a static cache.

evmrs: add feature "thread-local-cache"

---

go/integration_test/interpreter/dynamic_gas.go
go/integration_test/interpreter/verify_gas_test.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter_test.go

Because the CT would still fail, not charging 25000 Gas in scenarios where it should have done it.

LFVM: Revert selfdestruct empty vs. exists bug.

---

rust/Cargo.toml
rust/scripts/bench.sh

- change release profile to build with full lto and only one code gen unit to produce more performant binaries
- fix bench.sh

evmrs: build with lto and one code gen unit

---

go/ct/st/stack.go
go/interpreter/lfvm/ct_test.go

Adding stack releases in lfvm/ct tests, produced some tests to fail.
This was because stacks returned to the stack pool were not cleaned when returned neither when requested.
this small fix adds stack releases to tests and ensured ct's `NewStack` calls have the correct size and values.

CT: clear NewStack from pool

---

go/ct/utils/adapter.go
go/integration_test/interpreter/dynamic_gas.go
go/integration_test/interpreter/integration_test.go
go/integration_test/interpreter/test_evm.go
go/integration_test/interpreter/verify_gas_test.go
go/interpreter/evmc/evmc_interpreter.go
go/interpreter/geth/geth.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/interpreter/lfvm/interpreter_test.go

This PR replaces all Account-Exist checks in interpreters with Account-IsEmpty checks.
As was discovered by running the Ethereum tests and studying the new Python based EVM specification, interpreter implementations should have no dependency to the existence of an account. Their only concern should be the emptiness of an account in contexts where gas prices for the implicit creation of accounts need to be computed or the hash of an external account should be determined.
This PR introduces the following changes:
- fixes a bug in the geth reference-interpreter integration where an empty account was incorrectly identified by checking for its non-existence; while this is true for any finalized state on the chain (non-empty accounts must not exist), empty accounts may temporary exist during …

Replace all Exist checks with Empty checks in interpreters

---

.github/workflows/rust.yaml

With feature powerset testing, CO takes way to long. Currently clippy needs ~30min. Add a couple more features and it is in the hours. This PR changes how cargo hack is called. With the `--each-feature` flag each feature is tested individually, but no longer all feature combinations. Additionally it tests with no and all features.

evmrs: limit ci feature combinations to no, each and all features

---

rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/benchmarks/src/lib.rs
rust/src/interpreter.rs
rust/src/types/cache.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/mod.rs
rust/src/utils/helpers.rs

replace set_to_zero() by fill(0)
rename jump analysis to code analysis
rename feature jump-cache to code-analysis-cache
use saturating_sub in CodeReader::get_push_data

evmrs: refactor

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

The execution of the ethereum tests surfaced a bug in the error conversion between geth and tosca. If the maximum call depth is reached, the call was not successful but all its gas is returned. The same behavior is expected in an nonce overflow. 
Further, errors exceeding the max init code size were not handled in the conversion.

Geth adapter: Fix error conversion

---

go/ct/rlz/parameters.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

This bug was first found through the Ethereum json tests.
When a `CALL` command is executed and the top of the stack is a value bigger than `maxInt64` but smaller than `maxUint64` this value was still considered accepted and overflowed when converted to uint64. 
This PR:
- expands CT `gasParameter` to include values over max int64
- add fix in the lfvm interpreter
- adds a test that fails without the fix in lfvm

CT/LFVM: call provided gas over int64

---

go/ct/spc/specification.go
go/ct/st/call_journal.go
go/ct/st/call_journal_test.go
go/geth_adapter/adapter.go
go/interpreter/geth/ct.go
go/interpreter/geth/geth.go
go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go
go/tosca/interpreter.go

Thanks to the Ethereum json tests we found that all call kinds are expected to forward `CodeAddress`, We did not interpret this in CT nor the LFVM, so they are both fixed to reflect this new understanding. 
- To reflect this in the CT representation of the state, `CodeAddress` is added to `PastCalls` of the `CallJournal`.
- For the specification, in the `callEffect` used for the different call kinds, `CodeAddress` is initialized to the second parameter for all call kinds. 
- For geth, in `createGethInterpreterContext` there is yet no concept of the stack value, so it has to be modified forwarded in `geth/ct.go` where each call forwards the corresponding parameters into the corresponding call. 
- A test is added in LFVM to ensure correct call parameter usage depending on call kind.

Calls* forward code address

---

go.mod

This PR aligns the go version and toolchain configuration to those of other projects.
It also fixes a problem on some system where go version `1.22` is not a valid version specifier and something like `1.22.0` is required.

Fix go version settings

---

go/interpreter/lfvm/instructions_test.go

A small fix for a flaky unit test. The top-element of the stack should only be checked if the operation was successful.

Fix flaky TestBlobHash test

---

rust/src/types/code_reader.rs

This PR fixes a bug when there are fewer bytes than the push needs.
Not sure how this was never caught by CT before.

evmrs: fix push with fewer bytes that push len

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

The ethereum substate started to fail starting with the first Paris revision block. This was caused by the MergeNetSplitBlock not being set. In order to not run into this problem in the future, the revision selection inside the geth adapter is now leveraged to the geth's ChainConfig rules. 
Check compatibility

Geth adapter: Revision depending on geth rules

---

go/ct/spc/specification.go

This PR addresses the following issues:
- Thanks to the new interpretation of "empty" vs "exists" a missing case emerged for extcodehash, where an account was tested to be cold or warm, but not "not empty". 
the rules introduced by the cross product were tested both against geth as well as the lfvm.

CT: add missing rules for extcodehash

---

go/interpreter/lfvm/instructions_test.go

The stack output should only be checked in case there was no error. Same as #910.

LFVM: Fix flaky Blob unit test

---

go/ct/driver/run.go

CT states are skipped if the program counter points to data. This is known and understood, therefore it is not required to count and print the number of occurrences.
Solves #739.

CT: Remove skipped counter

---

Makefile

- No new errors detected. 
- No compatibility issues with go 1.22.
part of #675

Lint. Update errcheck version.

---

rust/src/types/amount.rs

This PR optimizes some operations on u256. This improves performance by 10%.
In particular `bytes.iter().take(24).any(|b| *b > 0)` is way slower than a comparison with `&[0; 24]`.

evmrs: optimize u256 operations

---

go/integration_test/interpreter/vm_test.go
rust/BUILD.md
rust/Cargo.toml
rust/bencher/src/main.rs
rust/scripts/bench.sh
rust/scripts/run_ct.sh

- make a clean build when benchmarking
- remove bench.sh
- clean go cache before running tests
- build with coverage when --all-features is set (otherwise linking fails)
- add jumptable-tail-call to performance feature
- update BUILD.md
- call b.Run in BenchmarkStaticOverhead to make regex matching possible (the run input is split along / with each split-string treated as a regex)

evmrs: make clean build when benchmarking

---

go/ct/evm_fuzz_test.go
go/ct/st/state.go

This PR adds a limit to the memory expansions generated by fuzzing tests. Nightly fuzzing has crashed a few times and the problem is attributed to large memory allocations. 
The CT has a [limit](https://github.com/Fantom-foundation/Tosca/blob/7b33705a4675b39f52859e2aadcbb9b69d3e9805/go/ct/st/state.go#L44) to the available gas for the execution of an instruction, large enough for a 450MB allocation. This limit may be too high for `FuzzDifferentialLfvmVsGeth`. During fuzzing, two resulting states are created by executing both geth and lfvm. This doubles the memory expansion.
The offending corpus: 
```
go test fuzz v1
[]byte("\xa0") 
int64(499_999_999_947)   
byte('\x04')
[]byte("\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x …
```

Fuzzing VMs: Limit memory usage

---

rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/interpreter.rs

- rename feature jumptable-tail-call -> tail-call
- do not enable feature jumptable when feature tail-call is enabled
This makes it possible to use the tail-call feature also for switch dispatch (and the upcoming feature opcode-fn-ptr-conversion)

evmrs: make feature tail-call available for all dispatch methods

---

rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/interpreter.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/mod.rs
rust/src/types/op_fn_data.rs
rust/src/types/opcode.rs
rust/src/types/pc_map.rs

This PR translates each opcode to a struct holding an optional function pointer and an u256 as data. This translation is caches as part of the code analysis. This improves performance by 20%.

evmrs: add feature opcode-fn-ptr-conversion

---

.github/workflows/rust.yaml
rust/src/interpreter.rs
rust/src/types/mock_execution_message.rs

This PR adds a test which makes sure tail calls are eliminated in release mode. This is necessary because otherwise, with sufficiently operations executed, the stack will overflow if feature tail-call is enabled.

evmrs: test tail call elimination

---

go/integration_test/interpreter/stress_test.go

The lfvm is using multiple caches to improve performance. To ensure that these caches are not a bottleneck when a high number of concurrent calls are performed, stress tests are developed. 
Solves #694.

Add interpreter stress tests

---

rust/Cargo.toml
rust/src/interpreter.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/mod.rs
rust/src/types/op_fn_data.rs
rust/src/types/opcode.rs

This PR adds the feature "opcode-fn-ptr-conversion-inline". This feature is similar to "opcode-fn-ptr-conversion" but instead of storing an optional function pointer and an u256 (40 bytes in total), it does the following:
- use [u8; 8] with alignment 8
- use the most significat byte to distinguish between jumpdest, normal opcodes and data
- in case of jumpdest and normal opcodes store the function pointer in the lower 6 bytes (linux pointers only need 6 bytes)
- in case of data use the lower 4 bytes to store up to 4 bytes of data
Most of the changes are just changes to the attributes because both features share a lot of code and some changes to tests because signatures and semantics change slightly.
The important changes are:
- code_analysis.rs: CodeAnalysis::analyze_code
- …

evmrs: add feature "opcode-fn-ptr-conversion-inline"

---

go/integration_test/interpreter/vm_test.go
rust/scripts/pgo.sh

This PR adds a bash script to create a pgo optimized version of evmrs. In order to to so the benchmarks have to dump instumentation data.
Unfortunately this does not work if feature tail-call is enabled because in segfaults, likely because the tail calls are no longer optimized away when instrumented and therefore trigger a stack overflow.
```
goos: linux
goarch: amd64
pkg: github.com/Fantom-foundation/Tosca/go/integration_test/interpreter
cpu: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
│ without-pgo  │              with-pgo               │
│    sec/op    │   sec/op     vs base                │
StaticOverhead/1/evmrs     2.490µ ± 1%   2.401µ ± 0%   -3.57% (p=0.000 n=20)
Inc/1/evmrs                5.835µ ± 3%   5.668µ ± 1%   -2.87% (p=0.000 n=20)
Inc/10/evmrs               6.011µ ± 2% …
```

evmrs: pgo setup

---

.github/workflows/rust.yaml
rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/interpreter.rs
rust/src/lib.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/mod.rs
rust/src/types/op_fn_data.rs
rust/src/types/opcode.rs

This PR adds helper features to clean up the feature guards. Those features are not meant to be used on their own and will explicitly fail to compile with a message explaining which features to enable. In addition some features have been renamed.
Renamed features:
- jumptable -> jumptable-dispatch
- opcode-fn-ptr-conversion -> fn-ptr-conversion-expanded-dispatch
- opcode-fn-ptr-conversion-inline -> fn-ptr-conversion-inline-dispatch
Helper features:
- needs-cache
- needs-jumptable
- needs-fn-ptr-conversion

 evmrs: add partial features to simplify feature guards 

---

rust/src/interpreter.rs
rust/src/types/status_code.rs
rust/src/utils/gas.rs
rust/src/utils/helpers.rs

This PR removes all checks for revisions < Instanbul because support for those is not needed and it is assumed that the revision is always at least Istanbul.

evmrs: remove revisions older than Istanbul

---

go/interpreter/evmrs/evmrs.go
rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/types/amount.rs
rust/src/types/mod.rs
rust/src/types/observer.rs
rust/src/types/stack.rs

This PR adds a logging version of evmrs. It works similar to how it is done in evmzero. The run method is now generic over an Observer. If the NoOpOberver is used, the calls to pre_op and post_op are no ops and should be eliminated by the compiler. The LoggingProfiler prints the state of the interpreter.

evmrs: add logging interpreter

---

rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/op_fn_data.rs

This PR adds the possibility to skip the step check (checking if steps are set and > 0) and jumpdests (by executing them inside jump / jumpi). This is then enabled for the non-steppable interface.
This only works when feature tail-call is not enabled, and improves performance here by about 10%.

evmrs: skip jumpdest and step check

---

.github/workflows/rust.yaml
rust/BUILD.md
rust/Cargo.lock
rust/Cargo.toml
rust/fuzz/.gitignore
rust/fuzz/Cargo.toml
rust/fuzz/fuzz_targets/evmc_execute.rs
rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/types/amount.rs
rust/src/types/memory.rs
rust/src/utils/gas.rs
rust/src/utils/helpers.rs

- add a fuzzer target for the evmc execute interface
- run fuzzer in CI (10s only) to make sure setup works
- document in BUILD.md how to run miri and fuzzer
- handle gas over-/underflow
- add GasRefund type

evmrs: add fuzzing

---

rust/src/interpreter.rs
rust/src/types/amount.rs

This PR optimizes the conversions u256 <-> U256.
The conversion u256 -> U256 before had a call (because for what ever reason U256::from_be_slice was not inlined) and a jump (for the unwrap). Both of those are now gone.
Additionally the conversions u256 <-> U256 are now also used for the conversions u256 <-> I256 and u256 <-> U512.
Unfortunately this does not improve performance, however I think it is still worth changing.

evmrs: optimize u256 <-> U256 conversion

---

rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/types/memory.rs
rust/src/utils/gas.rs
rust/src/utils/helpers.rs

This PR fixes a performance regression introduced in #942. It mainly affected the static overhead and therefore all short benchmarks.
Instead of returning an error when the gas is negative, the gas is now just set to 0 and will then return out-of-gas error once the first opcode is executed. This has the advantage that the case for negative gas no longer needs to be handled explicitly.

evmrs: fix performance regression introduced in #942

---

rust/src/types/amount.rs

This PR sets the alignment of u256 to 16 bytes. This is faster than 8 or 32 byte alignment.
The reason for being faster than 32 byte alignment seems to be that on x86, stacks are 16 byte aligned. When using 32 byte alignment the stack has to be realigned which is not necessary for 16 byte alignment.
Comparison with 8 byte alignment:
```
│ 2024-11-24T14:47#fbcd8b2#20/evmrs#performance │ 2024-11-24T15:08#fbcd8b2#20-align16/evmrs#performance │
│                    sec/op                     │            sec/op              vs base                │
StaticOverhead/1/                                      2.464µ ± 1%                     2.441µ ± 1%   -0.91% (p=0.015 n=20)
Inc/1/                                                 5.263µ ± 0%                     5.116µ ± 0%   -2.78% (p=0.000 n=20) …
```

evmrs: set alignment of u256 to 16

---

rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/types/stack.rs

With feature stack-array, the evm stack (32k) is stored on the program stack. This blows up the stack size and causes the max-call-depth test to crash with a stack overflow.
By putting the evm stack on the heap (Box<[MaybeUninit<u256>; 1024]>) this can be avoided with no noticable performance impact.
After some investigation, it turns out that speedup of the implementation using the Box got over the naive implementation using a Vec, was because the vector was checking if it has to grow on every push.
By eliminating that check with some unsafe code (which uses the fact that the vector gets created with a capacity of 1024 and therefore growing is never necessary) both implementations have similar performance. With some more unsafe code swap_with_top and nth can be written such that they …

evmrs: remove feature stack-array and add feature unsafe-stack

---

rust/src/evmc.rs
rust/src/interpreter.rs

Now that the evm stack is stored on the heap and the Interpreter type is small again, the api can be refactored somewhat.
This PR changes Interpreter::run such that it consumes the interpreter and returns either an ExecutionResult or a StepResult.

evmrs: consume Interpreter in run method and return Step- or ExecutionResult

---

.github/workflows/rust.yaml
rust/Cargo.toml
rust/fuzz/fuzz_targets/evmc_execute.rs
rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/observer.rs
rust/src/types/op_fn_data.rs
rust/src/utils/helpers.rs

This PR has the overarching goal of excluding the step check also when feature tail-call is enabled. In order to do so, instead of having various methods generic, now whole types are generic (Interpreter, OpFn, CodeAnalysis, ...). This makes it possible to call the correct version of Interpreter::next from an opcode impl, which is needed for tail-calls.
Other changes:
- merge const generics STEP_CHECK and JUMPDEST into a single const generic STEPPABLE
- implement Interpreter::new only for Interpreter<false> and Interpreter::new_steppable for Interpreter<true>. This avoids having to provide the generic argument explicitly and makes it impossible to misuse the api.
```
│ 2024-11-25T15:30#e4391e3#20-main/evmrs#performance │ 2024-11-27T09:42#20243ba#10/evmrs#performance │
│ …
```

evmrs: skip step check in tail calls

---

rust/benchmarks/src/lib.rs
rust/fuzz/fuzz_targets/evmc_execute.rs
rust/src/interpreter.rs
rust/src/types/amount.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/execution_context.rs
rust/src/types/hash_cache.rs
rust/src/types/memory.rs
rust/src/types/mock_execution_message.rs

This PR changes the u256 type to hold a U256 instead of [u8; 32]. Before it was expected that the bytes in [u8; 32] are in big endian, while U256 is little endian. With this change, it is no longer necessary to convert to little endian and back when doing arithmetic operations. However, call data load, mstore, mload and push have to do the conversion now. However the benchmarks show that this is faster. Further more the conversion for push can be done in the code analysis (for feature fn-ptr-conversion-expanded-dispatch), which gets cached.
```
│ 2024-11-27T18:12#1207189#20-main/evmrs#performance │ 2024-11-29T08:27#5f23203#10/evmrs#performance │
│                       sec/op                       │       sec/op         vs base                  │
StaticOverhead/1/ …
```

evmrs: use little endian for u256 (and stack)

---

go/ct/driver/regressions.go
go/ct/driver/run.go
regression_inputs/pc_on_data_#918.json

As fixed in #918, states with the program counter pointing to data should be skipped. This PR adds a regression input and adds the skipping of states to the regression driver.

CT: Skip states with PC on data

---

.github/workflows/rust.yaml
rust/Cargo.lock
rust/Cargo.toml
rust/src/types/execution_context.rs
rust/tests/ffi.rs

This PR bumps the evmc dependency when feature custom-evmc is enabled. The [new version](https://github.com/LorenzSchueler/evmc/commit/3d75575daa32e3563488361ffce84edf17109c74) no longer loads the TxContext eagerly but only when needed.
This improves performance of short running benchmarks by up to 30%.
```
│ 2024-12-04T15:51#50f8631#20-main/evmrs#performance │ 2024-12-04T17:38#cbb69de#20/evmrs#performance │
│                       sec/op                       │        sec/op          vs base                │
StaticOverhead/1/                                           2.602µ ± 0%             1.830µ ± 0%  -29.69% (p=0.000 n=20)
Inc/1/                                                      5.283µ ± 0%             4.240µ ± 0%  -19.74% (p=0.000 n=20)
Inc/10/ …
```

evmrs: lazy load TxContext

---

rust/src/types/amount.rs

This PR implements addition and subtraction of u256 using the addition/ subtraction of pairs of u128. Currently the addition and subtraction is done using the type U256 which implements it using u64.
This improves performance of the arithmetic benchmarks, but decreases performance of all short running benchmarks. It is not clear to me why short running benchmarks are negatively affected. Also when running e.g. StaticOverhead in isolation, the slowdown is less significant.
```
│ ../2024-12-04T15:51#50f8631#20-main/evmrs#performance │ 2024-12-03T08:50#eeba84d#20/evmrs#performance │ 2024-12-04T13:49#eeba84d#20/evmrs#performance │ 2024-12-04T14:06#eeba84d#20/evmrs#performance │ 2024-12-04T16:45#eeba84d#20/evmrs#performance │ 2024-12-04T16:46#eeba84d#20/evmrs#performance │
│ …
```

evmrs: impl add and sub using u128

---

rust/src/evmc.rs
rust/src/interpreter.rs
rust/src/types/memory.rs

This PR reuses the allocation for the memory by putting it into a Mutex<Option<_>> when dropping the memory and retrieving it from there in the constructor. This is similar to #961 but for the memory instead of the stack.
```
│ 2024-12-05T12:53#35e66b0#20-main/evmrs#performance │ 2024-12-05T13:36#eee2456#20/evmrs#performance │
│                       sec/op                       │         sec/op          vs base               │
StaticOverhead/1/                                           1.891µ ± 1%              1.888µ ± 1%       ~ (p=0.394 n=20)
Inc/1/                                                      4.264µ ± 0%              4.167µ ± 0%  -2.27% (p=0.000 n=20)
Inc/10/                                                     4.243µ ± 1%              4.159µ ± 1%  -1.99% (p=0.000 n=20)
Fib/1/ …
```

evmrs: reuse memory

---

rust/Cargo.lock
rust/Cargo.toml
rust/fuzz/fuzz_targets/evmc_execute.rs
rust/src/interpreter.rs
rust/src/types/amount.rs

This PR uses ethnum instead of bnum for the arithmetic operations, except for addmod and mulmod because those are not yet supported (see https://github.com/nlordell/ethnum-rs/issues/10).
In the Rust implementation of ethnum u128 is used as the base type which is faster than u64 as observed in #959.
ethnum also has a llvm-intrinsics feature which uses the llvm 256 bit integer type. However, even with linker-plugin-lto I did not get it to inline those functions and without inlining this is slower than the pure Rust implementation.
```
│ 2024-12-06T12:40#6196d42#20-main/evmrs#performance │ 2024-12-06T14:20#b22d4e4#20/evmrs#performance │
│                       sec/op                       │        sec/op          vs base                │
StaticOverhead/1/ …
```

evmrs: use ethnum

---

rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/types/memory.rs
rust/src/types/stack.rs

Currently only a single allocation for the stack and memory are reused. This PR changes that. Additionally it puts the code for reusing allocations behind the new feature alloc-reuse which is enabled when feature performance is enabled.
```
│ 2024-12-06T23:04#182aa20#20-main/evmrs#performance │ 2024-12-07T11:13#75e31d4#20-reuse-multiple/evmrs#performance │
│                       sec/op                       │                sec/op                  vs base               │
StaticOverhead/1/                                           1.782µ ± 1%                             1.764µ ± 1%  -1.04% (p=0.003 n=20)
Inc/1/                                                      3.681µ ± 1%                             3.716µ ± 0%  +0.95% (p=0.000 n=20)
Inc/10/ …
```

evmrs: add feature alloc-reuse and reuse multiple instances for stack and memory

---

BUILD.md
rust/BUILD.md
rust/driver/src/lib.rs
rust/llvm-profile-wrappers/src/lib.rs
rust/src/interpreter.rs
rust/src/lib.rs
rust/src/types/amount.rs
rust/src/types/code_analysis.rs
rust/src/types/op_fn_data.rs
rust/src/utils/generic_static.rs
rust/src/utils/mod.rs

This PR reduces the amount of unsafe code by:
- using unsafe extern blocks (see https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html#safe-items-with-unsafe-extern). The idea here is that you only assert once (at the declaration site) that the extern functions have indeed the signature and afterwards it is then safe to call those functions.
- passing optional references instead of pointers
- consolidating the custom solution for generic statics over const bool in the trait GetGenericStatic
Note: these changes require Rust 1.82, so because we have to increase the MSRV, we might as well use 1.83.

evmrs: reduce unsafe code

---

rust/src/types/execution_context.rs

With feature custom-evmc the signature of `ExecutionContext::get_tx_context` changed and needs a mutable reference. Because the signature of ExecutionContext was different, it used `<ExecutionContext as ExecutionContextTrait>::get_tx_context` instead which leads to infinite recursion.

evmrs: fix get_tx_context call forwarding

---

rust/Cargo.lock
rust/Cargo.toml
rust/llvm-profile-wrappers/Cargo.toml
rust/llvm-profile-wrappers/build.rs

In order to make the c compilation work also on other platforms, this PR uses the cc crate which calls the platform c compiler instead of calling gcc directly.
It also uses a fixed up the version of evmc-vm (and evmc-sys) which now also builds on windows.

evmrs: cross platform compilation

---

Makefile
rust/BUILD.md

In the Makefile and BUILD.md evmrs is now build with feature performance by default. Additionally the BUILD.md was updated. The optimization workflow section was removed because it only applied to adding optimizations behind feature flags. Instead the benchmarking and profiling sections now contain more information.

evmrs: update BUILD.md and build with feature performance in makefile

---

go/processor/floria/processor.go
go/processor/floria/processor_test.go

For the access list introduced in the Berlin revision, the sender is always warm and the account which storage keys are warm is also marked as warm.

Floria: Fix access list

---

go/processor/floria/state_contract.go
go/processor/floria/state_contract_test.go

The nonce in the state contract has been set with the wrong endian.

Floria: state contract fix nonce endian

---

go/processor/floria/processor.go
go/processor/floria/processor_test.go

The check regarding the nonce and the non externally owned accounts have to performed in the beginning of the transaction, therefore these checks are refactored. Further, a check for the max init code size is added.

Floria: Add nonce and eoa check

---

go/processor/floria/precompiled.go
go/processor/floria/run_context.go
go/processor/floria/run_context_test.go
go/processor/floria/state_contract.go

The overlapping code between all 4 call types and 2 create types is not big enough to justify all the if checks, therefore the call function is split into calls and creates.
With this change checks required for the create instructions have been added and the call instructions have been simplified.

Floria: Split call into calls and creates

---

go/processor/floria/processor.go
go/processor/floria/processor_test.go

With the changes in the run context it is no longer required to have special error cases in the processor. 
Some simple refactorings were also performed.

Floria: Remove wip error handling
