go/ct/spc/enumeration_test.go
This PR replaces the runtime dependent counting of active go-routines with a explicit mechanism counting the number of concurrent state processors.
Fixes #436
=> Fix flaky test regrading number of parallel jobs

go/vm/lfvm/ct.go, go/vm/lfvm/gas.go, go/vm/lfvm/instructions.go, go/vm/lfvm/interpreter.go, go/vm/lfvm/interpreter_test.go
This PR changes the revision bools for vm.Revision enums in lfvm
This PR fixes #396
=> LFVM:  revision enum

go.mod, go.sum, go/vm/geth/ct.go
Some changes needed on the Tosca sit to fit the simplified Tosca integration code in go-ethereum.
=> Update to simplified Tosca integration in Geth

go/ct/common/opcodes.go, go/ct/common/opcodes_test.go, go/ct/common/revisions.go, go/ct/rlz/conditions.go, go/ct/spc/specification.go
=> Add CT support for PUSH0

go/ct/driver/cli/utils.go, go/ct/driver/regressions.go, go/ct/driver/run.go, go/ct/driver/stats.go, go/ct/driver/test.go
This PR adds common flag cpuprofile on all relevant commands
=> CT: AddCommonFlags

go/ct/gen/code.go, go/ct/gen/code_test.go
I would handle the code size limit like this.
=> Add optional code size constraint to CodeGenerator

go/ct/spc/specification.go
This PR updates a few specification rules so that they can also accept states with Paris and Shanghai revisions.
=> CT: update specification rules to Shanghai in revision ranges

go/ct/common/words.go, go/ct/common/words_test.go, go/ct/spc/specification.go, go/ct/st/memory.go
This PR affects the specification
=> Add offset aware routine to count words in size operations.

cpp/vm/evmzero/interpreter_test.cc, go/ct/common/opcodes.go, go/ct/gen/block_context.go, go/ct/gen/block_context_test.go, go/ct/spc/specification.go, go/ct/st/block_context.go, go/ct/st/block_context_test.go, go/ct/utils/adapter.go, go/vm/geth/geth.go
This PR adds the `BLOBBASEFEE` opcode and rules, with the corresponding infrastructure for the converters, and generators.
This PR adds to #468 
This PR depends on #504
=> CT: Add BlobBaseFee 

go/integration_test/processor/processor_test.go, go/integration_test/processor/scenario.go, go/processor/floria/processor.go, go/processor/floria/processor_test.go, go/tosca/types.go
This PR registers Floria (Tosca's own processor implementation) to the processors to test. Functionality for a simple value transfer is also added. 
Fixes #568.
=> Floria: Registration and simple value transfer

go/interpreter/lfvm/instructions.go
Since the code for all 4 different kinds if call operations is mostly the same, whenever a bug is found in one, it most likely also applies for all of them, it makes it more maintainable to have a single implementation with the few parts that are specific for each kind guarded. 
This PR does exactly that, unifies the `opCall`, `opCallCode`, `opStaticCall` and `opDelegateCall`. To verify that these changes do not modify the expected behaviour, all operations ran against the CT and Geth.
This PR depends on #613
=> LFVM: unify calls

go/examples/analysis.go, go/examples/arithmetic.go, go/examples/example.go, go/examples/fib.go, go/examples/inc.go, go/examples/memory.go, go/examples/sha3.go, go/integration_test/processor/examples_test.go
To ensure transaction code is handled correctly by the processor and passed to the interpreter, the example codes are now also executed on a processor level. Output handling is also checked with these test runs. 
Examples with recursive calls should be added in the future.
Most of the changes in this PR are due to renaming to make fields and functions accessible outside of the examples package.
=> Run examples through processor

go/integration_test/processor/processor_gas_test.go, go/processor/floria/calls.go, go/processor/floria/calls_test.go, go/processor/floria/processor.go, go/processor/floria/processor_test.go
This PR adds gas computations and billing to Floria. A number of integration test cases stressing the setup gas computation have been added in #624.
=> Floria: Implement gas billing

go/integration_test/processor/calls_test.go
To ensure the different call types are implemented correctly more integration tests are added checking the call value, sender and whether it is in static context or not. All tests return the stressed property as the return value of the transaction.
=> Processor calls integration tests

go/integration_test/processor/calls_test.go, go/processor/floria/processor.go, go/processor/floria/run_context.go, go/processor/floria/run_context_test.go
This PR adds handling for different call types to Floria. 
Minor changes to the integration tests for the different call types are also part of this PR after the suggestions from @LuisPH3 on #633.
=> Floria: Implement different call types

.testcoverage.yml, go/ct/gen/assignment_test.go, go/ct/gen/state_test.go
This PR increases coverage of gen package.
in particular it adds a test for the string of `Assigment` and then a series of tests checking that calling the different methods that add different type of constraints to the state generator, are indeed adding the constraints.
=> Improve coverage gen package

rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs, rust/src/types/amount.rs, rust/src/types/mod.rs
add type `u256` and all methods required to implement opcodes later
=> Evmrs u256

.github/workflows/go.yml, Makefile
The aim of this PR is to make it so that we only a get a msg in a PR if the test has failed, but if the test succeeded, then no comment is needed
=> remove github wokflows that comments on PRs

rust/Cargo.lock, rust/Cargo.toml, rust/src/interpreter/mod.rs, rust/src/interpreter/stack.rs, rust/src/lib.rs, rust/src/types/amount.rs, rust/src/types/mod.rs
=> Add evmrs stack

go/integration_test/processor/calls_test.go, go/integration_test/processor/create_test.go
This PR adds integration tests stressing two properties of the processor:
1. Accounts can only be called if they exist
2. Accounts can only be created if they do not exist
=> Integration tests stressing existens of accounts

go/interpreter/lfvm/gas.go
This PR makes use of `constErr` in the gas errors, this facilitates future testing. 
It also adds a couple of comments listing operations in the ranges of early return in `getStaticGasPriceInternal`
=> LFVM: gas constErr

go/interpreter/lfvm/instructions.go
This PR fixes an error introduced by #720 in [this](https://github.com/Fantom-foundation/Tosca/pull/720/files#diff-6fc65a662dac0c86c1a3b0a634922f027d7796a0132d27a05064e9279ca85939R1199) line detected by the CT tests.
TODO:
=> Fix offset error introduced during refactoring

go/interpreter/lfvm/opcode.go, go/interpreter/lfvm/opcode_test.go
This PR adds two function to identify super instructions and and to decompose them into their basic instructions.
=> Add super-instruction decomposition support

rust/scripts/bench.sh, rust/scripts/test.sh
- add test bash script
- add bench bash script
=> evmrs: Add bench and tests scripts

go/interpreter/lfvm/converter.go, go/interpreter/lfvm/gas.go, go/interpreter/lfvm/hash_cache.go, go/interpreter/lfvm/memory.go, go/interpreter/lfvm/opcode.go, go/interpreter/lfvm/stack.go
While I was catching up on all the changes from the refactoring, I spotted a few cosmetic details. This PR consists of renaming, formating and other changes which do not alter any functionality.
=> LFVM: cosmetic code changes

go/interpreter/lfvm/ct.go, go/interpreter/lfvm/instructions.go, go/interpreter/lfvm/memory.go, go/interpreter/lfvm/memory_test.go, go/interpreter/lfvm/super_instructions.go
This PR simplifies memory's `set` function implementation and adds comprehensive unit testing.
=> LFVM: Improve memory's set implementation and associated unit tests

go/interpreter/lfvm/instructions_test.go, go/interpreter/lfvm/interpreter.go, go/interpreter/lfvm/interpreter_test.go, go/interpreter/lfvm/super_instructions.go
part of #751 
This test verifies that every jump operation does JUMPDEST check.
=> LFVM: Check jump instructions JUMPDEST test

.testcoverage.yml, BUILD.md, Jenkinsfile, Makefile, go/ct/driver/run.go, go/integration_test/interpreter/test_config.go, go/interpreter/evmrs/ct.go, go/interpreter/evmrs/ct_test.go, go/interpreter/evmrs/evmrs.go, go/interpreter/evmrs/evmrs_test.go
- build evmrs using make by invoking `cargo`
- integrate emvrs into Tosca
- include .cargo/bin in PATH for Jenkins
=> evmrs: go integration

go/interpreter/lfvm/instructions_test.go
part of #751 
This pr adds property-based tests for helper function
=> LFVM: Add test for getData helper function

.github/workflows/go-linter.yml, .github/workflows/go.yml, BUILD.md, Jenkinsfile, Makefile, go.mod
relates to #692
Triggered by https://github.com/Fantom-foundation/LaScala/pull/159
=> Update go version to 1.22

go/geth_adapter/adapter.go, go/geth_adapter/adapter_test.go
The geth adapter required some refactoring to enable unit testing.
Further, the revision conversion has been extended up to Cancun and the TODO regarding blobs has been fixed.
=> Refactor geth adapter

.testcoverage.yml, go/interpreter/lfvm/opcode.go
As a result of the recent efforts to increase coverage in the LFVM package, we can now upgrade this to ensure following work does not decreases coverage.
=> update lfvm coverage thresholds

Jenkinsfile
As an attempt to resolve a waiting time in a queue, this PR changes an agent type which doesn't use the same instance pool and the other regular tests.
=> Change jenkins agent

go/interpreter/lfvm/memory.go, go/interpreter/lfvm/memory_test.go
=> LFVM: Apply review changes from memory refactor

go/interpreter/lfvm/instructions_test.go
This PR adds a test for the out of gas case of `opReturnDataCopy`.
It also refactors a little bit the existing overflow test to improve readability. 
This PR is part of #751
=> LFVM: returnDataCopy out of gas test

go/interpreter/lfvm/instructions_test.go
This PR is part of #751.
As part of refining tests, we are making calls to runContextMocks, as specific as possible, hence removing uses to gomock.any()
=> LFVM: remove gomock.any in genericcall tests

go/interpreter/lfvm/instructions_test.go
part of #751 
This PR modifies existing tests to validate arguments passed to the run context calls, in context of transactions.
=> LFVM: Refactor test to validate transient storage run context calls. 

rust/Cargo.toml, rust/benchmarks/Cargo.toml, rust/src/evmc.rs, rust/src/interpreter.rs, rust/src/types/stack.rs
This PR adds the feature "stack-array". When this feature is enabled the Stack holds a [MaybeUninit<u256>; 1024] instead of Vec<u256>.
=> evmrs: add feature "stack-array"

rust/src/types/stack.rs
This PR changes the stack implementation such that instead of having a single Stack with different inner types depending on the feature "stack-array" there are now two separate Stack impls. This removed a lot of feature guards, makes it easier to read and keeps the checks inside of each implementation.
=> evmrs: make StackRaw a standalone stack impl and rename it to Stack

rust/Cargo.lock, rust/Cargo.toml, rust/src/interpreter.rs, rust/src/types/code_analysis.rs, rust/src/types/code_reader.rs
This PR removes some outdated comments and bumps all dependencies to their latest versions.
=> evmrs: cleanup

rust/src/ffi/evmc_vm.rs, rust/src/ffi/steppable_evmc_vm.rs
In this PR the ffi code is adjusted to no longer acquire ownership of the interpreter if not needed, but instead use a mutable reference. Before it was converted into a Box<_> and then the  box was release at the end.
=> evmrs: do not acquire ownership of interpreter if not needed

rust/src/types/stack.rs
This PR reuses the allocation for the stack by putting it into a Mutex<Option<_>> when dropping the stack and retrieving it from there in the constructor.
```
│ 2024-12-05T12:53#35e66b0#20-main/evmrs#performance │ 2024-12-05T13:12#30dd6c4#20/evmrs#performance │
│                       sec/op                       │         sec/op          vs base               │
StaticOverhead/1/                                           1.891µ ± 1%              1.756µ ± 0%  -7.11% (p=0.000 n=20)
Inc/1/                                                      4.264µ ± 0%              4.133µ ± 0%  -3.08% (p=0.000 n=20)
Inc/10/                                                     4.243µ ± 1%              4.116µ ± 0%  -2.99% (p=0.000 n=20)
Fib/1/                                                      3.763µ ± 1% …
```
=> evmrs: reuse stack
